[OBSDEF-11934] Add remedies for CRR alerts
EMCECS/charts pull request #1002
Opened 2021-09-15 12:40 UTC by dingr5

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-09-15 15:48 UTC, eddiepavkovic requested changes

2021-09-16 20:01 UTC, vgupta-mickey approved these changes

2021-09-16 23:57 UTC, eddiepavkovic requested changes

2021-09-16 23:57 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/12005_TARGET_OBJECTSTORE_FULL_issue.yaml
> +    -  Clean up some of the data in that objectstore to free up space for replication to continue
```suggestion
    - Add more space to the destination object store
    - Clean up some of the data in that object store to free up space for replication to continue
```
object store is always 2 words when used in sentences

2021-09-16 23:57 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/12006_REPLICATION_CERTIFICATE_ERROR.yaml
> +    - Contact Dell service to check or update TLS used for internal communication.
```suggestion
    - Check or update the TLS settings used for internal communication.
    - Contact the network administrator to assist in analyzing the configuration
```

2021-09-16 23:57 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/12007_REPLICATION_EVENT_RETRY_LIMIT_EXCEEDED.yaml
> +    - Contact Dell service to find replication issue and do manual retrigger for that event.
no... we shouldn't be telling them to contact dell for this,  why can't they fix this themselves.  only has a last resort should they contact dell services.

```suggestion
    - Check the network connection between the setups to ensure they're not running into network problems.
    - Review the events for this issue to determine which ends of the replication is not working correctly
    - Retry the replication once the issues have been resolved.
```

2021-09-17 03:44 UTC, dingr5 commented on ecs-cluster/alerts/remedies/12006_REPLICATION_CERTIFICATE_ERROR.yaml
> +    - Contact Dell service to check or update TLS used for internal communication.
Thanks for the suggestion, merged.

2021-09-17 03:55 UTC, dingr5 commented on ecs-cluster/alerts/remedies/12007_REPLICATION_EVENT_RETRY_LIMIT_EXCEEDED.yaml
> +    - Contact Dell service to find replication issue and do manual retrigger for that event.
Hi Eddie, this remedies is not for customer.

In CRR we have a side stream to collect events which current code have bug handling it. Once we know there is a bug handling this event (for example, event formatting does not match our protocol or some assumption not match), we will retry several times (some bug is a corner case which could pass after retry) and then put it in this side stream. To avoid infinate retry on this event and consume resource. 

This alert is raised only when an event is put in this side stream. This means the object will stays in pending state and no event will retrigger to do the replication, to notify OE or service team to take a look and find out why and put this event back to main stream. 

Please suggest if there is a proper way for this alert, if this kind of alert do not need remedies we can remove it.

2021-09-22 04:57 UTC, eddiepavkovic approved these changes
go ahead and merge.  we have to fix this up again in the next build.

2021-09-22 07:21 UTC, merged

2021-09-22 07:22 UTC, dingr5 commented
Thanks @eddiepavkovic