[OBSDEF-11193] Add the support to remove ObjectScale application
EMCECS/charts pull request #1005
Opened 2021-09-16 22:18 UTC by youminhan

## Purpose
[OBSDEF-11193](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-11193)
Add a pre-delete hook to remove all ObjectScale applications on Openshift.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing

`Dumpster` is down due to a network issue. Needs a final testing with charts.

2021-09-21 16:32 UTC, eddiepavkovic requested changes

2021-09-21 16:32 UTC, eddiepavkovic commented on objectscale-portal/values.yaml
>      tag: 0.82.0-769.a415d196 # rfw-update-this graphql-imagee
```suggestion
    tag: 0.82.0-769.a415d196 # rfw-update-this graphql-image
```
fix the rfw comment otherwise it won't be auto-updated during release.

2021-09-22 00:59 UTC, tmarcu commented on objectscale-portal/values.yaml
> +pullPolicy: Always
do you really want this change in or was it for testing only? The version isn't changing with this just the args for it right

2021-09-29 18:05 UTC, vgupta-mickey approved these changes

2021-09-29 19:02 UTC, eddiepavkovic approved these changes
g2g

2021-09-29 19:34 UTC, merged