[OBSDEF-12031] adding new shared secret to GraphQL
EMCECS/charts pull request #1021
Opened 2021-09-24 14:38 UTC by ben-schumacher

## Purpose
[OBSDEF-12031](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-12031)

Adding new shared secret to GraphQL.  Added two new env variables to GraphQL deployment.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-09-24 17:38 UTC, SeemaTahaliyani approved these changes

2021-09-30 13:03 UTC, vgupta-mickey requested changes

2021-09-30 13:03 UTC, vgupta-mickey commented on objectscale-graphql/templates/graphql-shared-secret.yaml
> +    "helm.sh/hook": "pre-install"
This pre-install will work only for OpenShift..how about VMware. The moment we upgrade the VMware package from version1 to version 2, it will recreate the secret. The intention for pre-install is that we don't want to refresh the secrets when we upgrade the release.

2021-09-30 20:58 UTC, vgupta-mickey approved these changes
Conditional approval to make sure that we take care upgrade issue as the secret will change for every upgrade. Either create a new story or some solution.

2021-09-30 21:08 UTC, merged