[OBSDEF-12181] [Enhancement] There should be an alert to specify if the pravega components are not ready/initialized
EMCECS/charts pull request #1022
Opened 2021-09-26 09:21 UTC by mmll

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-12181)
Add 1701 issue: pravega service is not ready
Change 1700 issue file name

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-09-26 14:42 UTC, eddiepavkovic requested changes
missing remedies for 1701...

2021-09-27 01:52 UTC, mmll commented
> missing remedies for 1701...

Done, thanks Eddie.

2021-09-28 07:08 UTC, CraneShiEMC approved these changes

2021-09-28 12:26 UTC, vgupta-mickey reviewed
Please review all the remedies for each symptom id  and make sure they all are making sense from the customer's point of view. It is up to the developer who knows what remedies are possible for a given problem.

2021-09-28 12:26 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/1700_PRAVEGA_CONNECT_issue.yaml
> +  component: Pravega
is Pravega itself generate this event?
which component container generates this event?
we should list out the name of the component that is generating this event.

2021-09-28 12:26 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/1701_PRAVEGA_SERVICE_NOT_READY_issue.yaml
> +  component: Pravega
same

2021-09-28 12:26 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/1700_PRAVEGA_CONNECT_remedies.yaml
> +  component: Pravega
same

2021-09-28 12:26 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/1701_PRAVEGA_SERVICE_NOT_READY_issue.yaml
> +  component: Pravega
same

2021-09-29 02:48 UTC, mmll commented on ecs-cluster/alerts/issues/1700_PRAVEGA_CONNECT_issue.yaml
> +  component: Pravega
This event is generated by stream lib which is used by ons, objmt or crr components. Does it mean we need to config the component as these 3 components?

2021-09-29 13:23 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/1700_PRAVEGA_CONNECT_issue.yaml
> +  component: Pravega
you can add the multiple components as a string as long the components are defined in  the owner reference document.

2021-09-29 17:09 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/1700_PRAVEGA_CONNECT_issue.yaml
> +  component: Stream
remove it..we just need to add into remedies

2021-09-29 17:09 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/1701_PRAVEGA_SERVICE_NOT_READY_issue.yaml
> +  component: Stream
same

2021-09-29 17:13 UTC, eddiepavkovic reviewed
why is there 1420 commits in this PR?  was this created from an older charts repo?
@pgraves5 ^^

2021-09-30 02:01 UTC, closed without merging