[OBSDEF-12244] Component name to OBJSOP- and OBJSC-SP- issues' remedies added
EMCECS/charts pull request #1029
Opened 2021-09-28 07:39 UTC by kirillston

## Purpose
[OBSDEF-12244](https://jira.cec.lab.emc.com/browse/OBSDEF-12244)

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-09-28 12:23 UTC, vgupta-mickey requested changes

2021-09-28 12:23 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/OBJSOP-1000_DISK_REPLACEMENT_remedies.yaml
> +  component: objectstore
if the operator is generating the event, it should;d be operator name. We want to make sure that we can find out the person based on the component who is responsible to the generate events. This event is generated on the objectstore but it is operator or sp-operator who is generating it.

2021-09-28 12:23 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/OBJSOP-1001_PMM_remedies.yaml
> +  component: objectstore
same

2021-09-28 12:23 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/OBJSOP-1002_TMM_remedies.yaml
> +  component: objectstore
same

2021-09-28 12:23 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/OBJSOP-1003_UPGRADE_remedies.yaml
> +  component: objectstore
same

2021-09-28 12:23 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/OBJSOP-1004_HORIZONTAL_EXPAND_remedies.yaml
> +  component: objectstore
same

2021-09-28 12:23 UTC, vgupta-mickey commented on ecs-cluster/alerts/remedies/OBJSOP-1004_VERTICAL_EXPAND_remedies.yaml
> +  component: objectstore
same

2021-09-28 12:23 UTC, vgupta-mickey commented on objectscale-manager/alerts/remedies/OBJSC-MGR-HC-1000_PRE_UPDATE_remedies.yaml
> +  component: objectscale-manager
I would say...you need to use specific component name - objectscale-operator or objectscale-sp-operator depending on who is generating it.

2021-09-28 12:23 UTC, vgupta-mickey commented on objectscale-manager/alerts/remedies/OBJSC-SP-0001_DISK_REPLACEMENT_remedies.yaml
> +  component: objectscale-manager
same

2021-09-28 12:23 UTC, vgupta-mickey commented on objectscale-manager/alerts/remedies/OBJSC-SP-0002_PMM_remedies.yaml
> +  component: objectscale-manager
same

2021-09-28 12:23 UTC, vgupta-mickey commented on objectscale-manager/alerts/remedies/OBJSC-SP-0003_TMM_remedies.yaml
> +  component: objectscale-manager
same

2021-09-28 12:23 UTC, vgupta-mickey commented on objectscale-manager/alerts/remedies/OBJSOP-2001-CSR_NOTIFICATIONS_remedies.yaml
> +  component: objectscale-manager
same

2021-09-28 12:23 UTC, vgupta-mickey commented on objectscale-manager/alerts/remedies/OBJSOP-2002-TLS_CERT_EXPIRY_remedies.yaml
> +  component: objectscale-manager
same

2021-09-28 13:57 UTC, kirillston commented on ecs-cluster/alerts/remedies/OBJSOP-1000_DISK_REPLACEMENT_remedies.yaml
> +  component: objectstore
Thank you for explanation, Vinod!
Changes are done

2021-09-28 13:57 UTC, kirillston commented on ecs-cluster/alerts/remedies/OBJSOP-1001_PMM_remedies.yaml
> +  component: objectstore
Done!

2021-09-28 13:58 UTC, kirillston commented on ecs-cluster/alerts/remedies/OBJSOP-1002_TMM_remedies.yaml
> +  component: objectstore
Done!

2021-09-28 13:58 UTC, kirillston commented on ecs-cluster/alerts/remedies/OBJSOP-1003_UPGRADE_remedies.yaml
> +  component: objectstore
Done!

2021-09-28 13:58 UTC, kirillston commented on ecs-cluster/alerts/remedies/OBJSOP-1004_HORIZONTAL_EXPAND_remedies.yaml
> +  component: objectstore
Done!

2021-09-28 13:58 UTC, kirillston commented on ecs-cluster/alerts/remedies/OBJSOP-1004_VERTICAL_EXPAND_remedies.yaml
> +  component: objectstore
Done!

2021-09-28 13:58 UTC, kirillston commented on objectscale-manager/alerts/remedies/OBJSC-MGR-HC-1000_PRE_UPDATE_remedies.yaml
> +  component: objectscale-manager
Done!

2021-09-28 13:58 UTC, kirillston commented on objectscale-manager/alerts/remedies/OBJSC-SP-0002_PMM_remedies.yaml
> +  component: objectscale-manager
Done!

2021-09-28 13:58 UTC, kirillston commented on objectscale-manager/alerts/remedies/OBJSC-SP-0003_TMM_remedies.yaml
> +  component: objectscale-manager
Done!

2021-09-28 13:58 UTC, kirillston commented on objectscale-manager/alerts/remedies/OBJSOP-2001-CSR_NOTIFICATIONS_remedies.yaml
> +  component: objectscale-manager
Done!

2021-09-28 13:58 UTC, kirillston commented on objectscale-manager/alerts/remedies/OBJSOP-2002-TLS_CERT_EXPIRY_remedies.yaml
> +  component: objectscale-manager
Done!

2021-09-28 14:21 UTC, vgupta-mickey approved these changes

2021-09-28 14:59 UTC, BassinD approved these changes

2021-09-29 03:27 UTC, eddiepavkovic requested changes

2021-09-29 03:27 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/OBJSC-SP-0000_RECOVERY_remedies.yaml
> +  component: objectscale-sp-operator
i think this now needs to be the jira component.

2021-09-29 06:04 UTC, antonbassin commented on ecs-cluster/alerts/remedies/OBJSC-SP-0000_RECOVERY_remedies.yaml
> +  component: objectscale-sp-operator
Jira components are not correct in general. do we have a kahm component for example?
operator and sp operator have different owners. 
Leave it as is, we will add the sp-operator jira component if needed.

2021-09-29 06:17 UTC, eddiepavkovic requested changes

2021-09-29 06:17 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/OBJSC-SP-0000_RECOVERY_remedies.yaml
> +  component: objectscale-sp-operator
The ask from mgmt is to use Jira components.  So that there's clear ownership

2021-09-29 07:16 UTC, closed without merging