[OBSDEF-12159] add pravega/zk security context
EMCECS/charts pull request #1038
Opened 2021-09-29 03:57 UTC by realAaronWu

## Purpose
[OBSDEF-12159](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-12159)
Add securoty context for pravega and zk pods, and init contianer for zk pods

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-09-29 04:02 UTC, eddiepavkovic requested changes

2021-09-29 04:02 UTC, eddiepavkovic commented on ecs-cluster/templates/ecs-cluster.yaml
> +      - mountPath: /data
This should be done in a Dockerfile.  not at runtime.

@Bjohnson131 @vgupta-mickey

2021-09-29 04:05 UTC, realAaronWu commented on ecs-cluster/templates/ecs-cluster.yaml
> +      - mountPath: /data
I tried to add permssion in Dockfile but it failed to take effect when contianer starts, the zk still got permission denied error when access /data.

2021-09-30 03:34 UTC, realAaronWu commented on ecs-cluster/templates/ecs-cluster.yaml
> +      - mountPath: /data
@eddiepavkovic  removed the initContainer and use fsGroup to set permission instead.

2021-10-01 08:08 UTC, BassinD approved these changes

2021-10-01 14:07 UTC, eddiepavkovic approved these changes
g2g

2021-10-01 14:08 UTC, merged