[MONITORING-1004] Tools for Alert report auto-generation
EMCECS/charts pull request #541
Opened 2020-12-18 18:15 UTC by nikolay-t

Generates this table https://confluence.cec.lab.emc.com/display/OBJSCALE/Autogenerated+ObjectScale+Alerts

2020-12-18 19:42 UTC, vgupta-mickey approved these changes
Very nice. Let's get this in and improve later if we find any issues.

2020-12-18 20:40 UTC, eddiepavkovic requested changes

2020-12-18 20:40 UTC, eddiepavkovic commented on Makefile
> +template-all:
can we rename this to `generate-issues-events-all`

2020-12-18 20:40 UTC, eddiepavkovic commented on tools/alert-report/alert_reporter.py
> +#!/usr/bin/python
can we rename the file to `issues_events_reporter.py` since we're capture all of the issues and events from all components in the charts.  not everything is an alert.

2020-12-18 20:40 UTC, eddiepavkovic commented on Makefile
> +	echo -n > ${TEMP_PACKAGE}/yaml/all.yaml
```suggestion
	echo -n > ${TEMP_PACKAGE}/yaml/issues_events_${FLEXVER}.yaml
```

2020-12-18 20:40 UTC, eddiepavkovic commented on tools/alert-report/alert_reporter.py
> +
Add the ${FLEXVER} $DECKSVER here inside the page so that we know what version these issues and events belong to.

2020-12-21 08:06 UTC, vazhem approved these changes

2020-12-21 14:22 UTC, nikolay-t commented on tools/alert-report/alert_reporter.py
> +  <ac:parameter ac:name="columns">SymptomId,name,description,issueCategory,notifiers,remedies</ac:parameter>
Done

2020-12-21 14:23 UTC, nikolay-t commented on Makefile
> +template-all:
Done

2020-12-21 14:23 UTC, nikolay-t commented on tools/alert-report/alert_reporter.py
> +#!/usr/bin/python
renamed

2020-12-21 14:23 UTC, nikolay-t commented on tools/alert-report/alert_reporter.py
> +        srec[sim]['remedies'] = rmd
ok

2020-12-21 14:23 UTC, nikolay-t commented on tools/alert-report/alert_reporter.py
> +
done

2020-12-22 03:38 UTC, eddiepavkovic approved these changes
Nice, thanks for making all the changes.  looks good.

2020-12-22 15:23 UTC, merged