release object scale 0.63
EMCECS/charts pull request #551
Opened 2020-12-28 06:24 UTC by garretwu

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2020-12-28 06:31 UTC, eddiepavkovic commented on Makefile
> +HELM_KAHM_ARGS       =  --set image.tag=${0.62}
No don't make the change here.   What I meant was change the make release to bypass 
Decks and kam versions for this. Build.

2020-12-29 02:09 UTC, garretwu commented on Makefile
> +HELM_KAHM_ARGS       =  --set image.tag=${0.62}
not quiet understand.
release target is as follows:
release: decksver flexver build-all generate-issues-events-all add-to-git

do you mean I need to update decksver target and skip "decks kahm" in DECKSCHARTS?

2020-12-29 02:15 UTC, eddiepavkovic commented on Makefile
> +HELM_KAHM_ARGS       =  --set image.tag=${0.62}
undo any changes in the Makefile.  i'll just retag all the decks/kahm/service-tools 62 images to 63 so that there's no confusion.

2020-12-29 02:35 UTC, garretwu commented on Makefile
> +HELM_KAHM_ARGS       =  --set image.tag=${0.62}
Done

2020-12-29 04:56 UTC, eddiepavkovic commented
ok good.  please do the following for the build.

1. Run `make release` to build out the charts
2. Add people to the reviewers list so that you can get 2 approvals.  
3. Fill out the checklist above
4. add yourself as assignee
5. Fill in the testing section

good luck.

2020-12-29 07:14 UTC, vazhem requested changes

2020-12-29 07:14 UTC, vazhem commented on Makefile
Please merge latest commits from master to your branch.
Unsure that 32115e6c95e37c1588d1cb0e8c585c0c021569a1 commit is present in your branch before you perform make release to build and tag charts

2020-12-29 09:51 UTC, fedor-chemashkin approved these changes

2020-12-29 10:27 UTC, vazhem approved these changes

2020-12-29 14:06 UTC, merged