[OBSDEF-4676] - Add direct access support in support assist
EMCECS/charts pull request #553
Opened 2021-01-04 08:43 UTC by fyang86

## Purpose
[OBSDEF-4676](https://jira.cec.lab.emc.com/browse/OBSDEF-4676)
add direct access support in support assist controller in decks, decks change in https://eos2git.cec.lab.emc.com/atlantic/decks/pull/101

## PR checklist
- [x] make test passed
- [x] make build passed
- [x] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing

2021-01-05 00:10 UTC, eddiepavkovic requested changes

2021-01-05 00:10 UTC, eddiepavkovic commented on supportassist/templates/supportassist-cr.yaml
> +  {{- end }}
we shouldn't require this from the customer.  this is an internal setting inside ese.

2021-01-05 00:10 UTC, eddiepavkovic commented on supportassist/values.yaml
> +
we shouldn't require this from the customer.  they don't know what to set here.  its built internally into the ESE code

2021-01-05 00:11 UTC, eddiepavkovic commented
converting to draft,  we can't ask customers to provide the directEndpoints params,  that's internal to dellemc

2021-01-05 02:48 UTC, fyang86 commented on supportassist/values.yaml
> +
so we shouldn't read the direct endpoint from support assist CR, just use it inside the ese code right?

2021-01-06 04:52 UTC, eddiepavkovic commented
closing this,  confirmed with Vaishali today that we only need to set `useGateways = false` and it'll auto use the direct connect setting.  no need to set endpoints its already internally configured.

2021-01-06 04:52 UTC, closed without merging