[OBSDEF-4831] Fix healthcheck RBAC
EMCECS/charts pull request #554
Opened 2021-01-04 23:43 UTC by tmarcu

The health checks run may need to list things like ecsclusters to figure out
if the state of the component is healthy (in objectstore-pre-update check's
case). Use a new job-runner service account for this which lets us fine tune
RBAC for health checks without overloading existing serviceaccounts. This
does not use the KAHM service account because job-runner covers only its
specific namespace, while kahm might have access to other namespaces.

Signed-off-by: Tudor Marcu <Tudor.Marcu@emc.com>

## Purpose
https://jira.cec.lab.emc.com/browse/OBSDEF-4831

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-01-04 23:47 UTC, spiegela approved these changes

2021-01-05 00:13 UTC, eddiepavkovic approved these changes
looks good, would be helpful to fill out the checklist and what testing was done.

2021-01-05 14:39 UTC, vgupta-mickey requested changes

2021-01-05 14:39 UTC, vgupta-mickey commented on kahm/templates/job-runner.yaml
> +  - apiGroups:
KAHM is a central component to monitor all kinds of applications across various namespaces if KAHM is watching the applications across the namespaces. I would never add specific CRD permissions into KAHM as Role or ClusterRole. I would like to keep KAHM as product and application-independent. So here is my proposal to fix this:

1. Each application knows how and what they are running in the health-check container. KAHM doesn't want to take that responsibility to add RBAC for each application and it shouldn't. KAHM has no business to micro-manage the RBAC rules for each application.
2.  That being said, each application (in our case Objectstore and Objectscale-manager), must create the service-account, role, and role-binding for their health-check container as a part of their own chart. The health-check configuration in the application configmap should provide the account name for KAHM to use it.
 
Please let me know if we need to discuss it further but it is a slippery slope of making KAHM product/application dependent.

2021-01-05 16:37 UTC, eddiepavkovic approved these changes
nice.

2021-01-05 16:40 UTC, tmarcu commented on kahm/templates/job-runner.yaml
> +  - apiGroups:
@vgupta-mickey good suggestion I made this change just now for both repos

2021-01-05 16:49 UTC, merged