[OBSDEF-4833] Fix being unable setup SupportAssist in different namespace once another one is already setup
EMCECS/charts pull request #555
Opened 2021-01-05 06:56 UTC by KimiJLXu

## Purpose
[OBSDEF-4388](https://jira.cec.lab.emc.com/browse/OBSDEF-4833)
Add namespace key for ClusterRole and ClusterRoleBinding to fix unable setup SupportAssist in different namespace once another one is already setup.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-01-05 14:59 UTC, eddiepavkovic submitted a review, later dismissed
ok

2021-01-05 16:08 UTC, vgupta-mickey requested changes

2021-01-05 16:08 UTC, vgupta-mickey commented on supportassist/templates/notifier-rbac.yaml
> +  namespace: {{ .Release.Namespace }}
There is no need for namespace in the clusterRole. The clusterRole is cluster scoped.

2021-01-05 16:08 UTC, vgupta-mickey commented on supportassist/templates/notifier-rbac.yaml
> +  namespace: {{ .Release.Namespace }}
same comment

2021-01-06 03:10 UTC, KimiJLXu commented on supportassist/templates/notifier-rbac.yaml
> +  namespace: {{ .Release.Namespace }}
yeah, I tested with the code before changing and you are right. This change is unnecessary. So I'm asking for more detail about the bug in JIRA to figure out the real root cause.

2021-01-06 03:20 UTC, eddiepavkovic commented on supportassist/templates/notifier-rbac.yaml
> +  namespace: {{ .Release.Namespace }}
You can test this yourself.  Just deploy support assist in 2 namespaces.  It should fail

2021-01-06 04:09 UTC, KimiJLXu commented on supportassist/templates/notifier-rbac.yaml
> +  namespace: {{ .Release.Namespace }}
I tested on Hulk yesterday and deploy support assist in 2 namespaces through GUI. It succeeded even I created cluster role binding with the same name before deploying SA. But it happened when I tried to deploy by helm install.
Does GUI deploy support assist by helm install or create through code?

2021-01-24 18:40 UTC, eddiepavkovic commented
closing as we couldn't reproduce the problem.

2021-01-24 18:40 UTC, closed without merging