Feature obsdef 3775 dcm charts
EMCECS/charts pull request #565
Opened 2021-01-11 22:06 UTC by sumithreddy

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-01-11 23:26 UTC, eddiepavkovic requested changes

2021-01-11 23:26 UTC, eddiepavkovic commented on dcm/values.yaml
> +  registry: asdrepo.isus.emc.com:8099
don't hardcode this registry as its not available outside of dellemc.

2021-01-11 23:26 UTC, eddiepavkovic commented on dcm/values.yaml
> +    registry: asdrepo.isus.emc.com:8200
don't hardcode internal registries.

2021-01-11 23:40 UTC, sumithreddy commented on dcm/values.yaml
> +  registry: asdrepo.isus.emc.com:8099
so take it out completely and let it use only global.registry ?

2021-01-14 12:34 UTC, fedor-chemashkin commented on dcm/templates/deployment.yaml
> +            value: "atlas,flex,dns"
should `crr` be here?

2021-01-14 12:34 UTC, fedor-chemashkin commented on dcm/values.yaml
> +  replicaCount: 3
Will it be always 3? What about not large profiles?

2021-01-14 21:12 UTC, sumithreddy commented on dcm/templates/deployment.yaml
> +            value: "atlas,flex,dns"
Not really. This might go in Beta 2
There is another feature flag which is introduced for object notifications, I don't think that feature flag is in charts repo yet

2021-01-14 21:13 UTC, sumithreddy commented on dcm/values.yaml
> +  replicaCount: 3
Atlas always requires min of 3 pods.
And even for larger profiles 3 should do!

2021-01-15 07:43 UTC, fedor-chemashkin approved these changes

2021-01-15 07:59 UTC, sumithreddy commented on dcm/values.yaml
> +    registry: asdrepo.isus.emc.com:8200
done

2021-01-15 07:59 UTC, sumithreddy commented on dcm/values.yaml
> +  registry: asdrepo.isus.emc.com:8099
done

2021-01-15 14:02 UTC, hldnova commented on dcm/values.yaml
> +  replicaCount: 3
with small profile in objectstore there is only one atlas pod. So it seems that atlas can work with just one pod. I think it should be made configurable, and deploy a single pod by default in small/micro profile. I remember seeing `global.performanceProfile=Small` in objectscale deployment. maybe that can be used to set replicas.

2021-01-15 22:27 UTC, eddiepavkovic approved these changes
ok looks great.  thanks

2021-01-15 22:30 UTC, merged