[OBSDEF-5242] added crds
EMCECS/charts pull request #615
Opened 2021-02-10 07:26 UTC by alexander-rassanov

## Purpose
[OBSDEF-5242](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5242)
Added CRDS

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-02-10 09:58 UTC, hoklet approved these changes

2021-02-10 14:01 UTC, eddiepavkovic requested changes

2021-02-10 14:01 UTC, eddiepavkovic commented on objectscale-manager/crds/storagepolicy.yaml
> +  name: storagepolicies.ecs.dellemc.com
we need to rename this,  it conflicts with storagepolicies on vsphere.

```
─ $ ▶  kubectl get storagepolicies
NAME                                    AGE
dellemc-objectscale-highly-available    13h
dellemc-objectscale-vsan-direct-thick   13h
dellemc-objectscale-vsan-sna-thick      13h

```

2021-02-10 16:04 UTC, alexander-rassanov commented on objectscale-manager/crds/storagepolicy.yaml
> +  name: storagepolicies.ecs.dellemc.com
fixed

2021-02-11 03:59 UTC, eddiepavkovic commented on objectscale-manager/crds/storagepolicy.yaml
> +  name: storagepolicies.ecs.dellemc.com
but this name is still storagepolicies...  which kinda conflicts with vsphere storagepolicies...  
```suggestion
  name: storagepolicies.ecs.dellemc.com
```

2021-02-11 03:59 UTC, eddiepavkovic commented on objectscale-manager/crds/storagepolicy.yaml
> +    singular: ecs-storagepolicy
jason wants us to not use `ecs` in the charts.  can we use `objectscale-storagepolicies`
```suggestion
    singular: ecs-storagepolicy
```

2021-02-11 09:42 UTC, alexander-rassanov commented on objectscale-manager/crds/storagepolicy.yaml
> +  name: storagepolicies.ecs.dellemc.com
However we have group ECS

2021-02-17 13:18 UTC, alexander-rassanov commented on objectscale-manager/crds/storagepolicy.yaml
> +    singular: ecs-storagepolicy
fixed

2021-02-17 13:18 UTC, alexander-rassanov commented on objectscale-manager/crds/storagepolicy.yaml
> +  name: storagepolicies.ecs.dellemc.com
is it ok for you?

2021-02-18 09:32 UTC, fedor-chemashkin approved these changes

2021-02-18 18:23 UTC, eddiepavkovic submitted a review, later dismissed
Alex i brought this up during our standup and they agreed we shouldn't be re-using a name already taken by VMware.  can we prefix this with something more unique or come up with a different name.

2021-02-20 09:33 UTC, alexander-rassanov commented
> Alex i brought this up during our standup and they agreed we shouldn't be re-using a name already taken by VMware. can we prefix this with something more unique or come up with a different name.

I changed the name and added prefix objectstore. The common name of the CRD is under dell.ecs group

2021-03-22 15:00 UTC, merged