[ATL-1512] Add fixed CSI alerts
EMCECS/charts pull request #619
Opened 2021-02-12 06:58 UTC by AnastasiaShemyakinskaya

## Purpose
[ATL-1512](https://jira.cec.lab.emc.com/browse/ATL-1512)

* Add CSI chart with fixed matchOnList

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-02-12 14:53 UTC, vgupta-mickey requested changes
You just need to  2 symptomID and  2  rules.
1)
- description: "Disk failure or suspect"
  name: "DiskProblems"
  issueCategory: Auto
  matchOnList:
    - matchon:
        - label: SymptomID
          value: 2002
  notifiers:
           add notifier if needed here.

   if the disk becomes good, added, or failure suspect or failed, they all will generate events with the same SymtomID = 2002 but the Type of the event will be  Critical for Failure, Warning for SUSPECT, and Normal for Good.
2) - description: "Disk Replacement issue or  missing"
  name: "DiskReplacementProblems"
  issueCategory: Auto
  matchOnList:
    - matchon:
        - label: SymptomID
          value: 2062
  notifiers:
           add notifier if needed here.

   if the disk replacement is failed, missing, replaced successfuly, they all will generate events with the same SymtomID = 2062 but the Type of the event will be  Critical for Failure, Warning for Missing, and Normal for Successfully Replacement.

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2002_DISK_FAILURE_issue.yaml
> +  notifiers:
do you need notification here?

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2019_DISK_ADD_issue.yaml
> +  name: "DiskAdded"
why DiskAdded is an issue? the issue rules are only for some problem which you want customer to have attention?

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2025_DISK_GOOD_issue.yaml
> +  name: "DiskGood"
why issue? the same comment as above.

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2062_DISK_REPLACEMENT_FAILED_issue.yaml
> +  issueCategory: Auto
how this issue will automatically clear?
which event would you send to clear this issue?
the application should  generate another event with the same SymptomID but Type: Normal.

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2063_DISK_MISSING_issue.yaml
> +  name: "DiskMissing"
how this issue will automatically clear?
which event would you send to clear this issue?
the application should generate another event with the same SymptomID but Type: Normal.

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2065_DISK_SUCCESSFULLY_REPLACED_issue.yaml
> +  name: "DriveSuccessfullyReplaced"
you don't need a new issue rule for this.

You should use the same symptomID as "DiskReplacementFailed" but  the type of the event should be "normal"
The message of the event will represent that the disk is successfully replaced.

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2003_DISK_SUSPECT_issue.yaml
> +  name: "DiskSuspect"
you don't need a new issue rule for this and you don't need new symtomID for this.

2021-02-12 14:53 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2025_DISK_GOOD_issue.yaml
> +  name: "DiskGood"
when a disk is declared good. you should generate an event with the same symtomID as "disk failure" symptomID.

2021-02-12 16:01 UTC, vgupta-mickey requested changes
```  - description: "Disk failure or suspect"
  name: "DiskProblems"
  issueCategory: Auto
  matchOnList:
    - matchon:
        - label: SymptomID
          value: 2002
    - matchon:
        - label: SymptomID
          value: 2003
    - matchon:
        - label: SymptomID
          value: 2019
    - matchon:
        - label: SymptomID
          value: 2025
  notifiers:
 description: "DiskReplacement issues"
  name: "DiskReplacementProblems"
  issueCategory: Auto
  matchOnList:
    - matchon:
        - label: SymptomID
          value: 2061
    - matchon:
        - label: SymptomID
          value: 2062
    - matchon:
        - label: SymptomID
          value: 2063
    - matchon:
        - label: SymptomID
          value: 2065
  notifiers:
 ```

2021-02-12 20:47 UTC, vgupta-mickey approved these changes

2021-02-15 12:11 UTC, mishoyama commented on ecs-cluster/alerts/issues/2019_DISK_ADD_issue.yaml
> +  name: "DiskAdded"
What if we want to show notification in UI? What type of alert `DiskAdded` event should be?

2021-02-15 12:13 UTC, mishoyama commented on ecs-cluster/alerts/issues/2002_DISK_FAILURE_issue.yaml
> +  notifiers:
Yes, what are the options available? Could you please share a link to the doc? Definitely don't want to send them home since we aren't responsible for HW in OpenShift...

2021-02-15 12:15 UTC, mishoyama commented on ecs-cluster/alerts/issues/2025_DISK_GOOD_issue.yaml
> +  name: "DiskGood"
services must be using symptomIDs for filtering and collecting different statistics. We have a requirements to support all ECS Classic alerts if relevant. Are your recommendations coming from PMs?

2021-02-15 12:16 UTC, mishoyama commented on ecs-cluster/alerts/issues/2062_DISK_REPLACEMENT_FAILED_issue.yaml
> +  issueCategory: Auto
No auto clear so far. CS will have to solve the problem and clear event manually.

2021-02-15 12:16 UTC, mishoyama commented on ecs-cluster/alerts/issues/2063_DISK_MISSING_issue.yaml
> +  name: "DiskMissing"
Not sure that we need to clear this event automatically. Someone should pay attention to this problem.

2021-02-15 12:17 UTC, mishoyama commented on ecs-cluster/alerts/issues/2003_DISK_SUSPECT_issue.yaml
> +  name: "DiskSuspect"
Same question about `symtomID` as above here.

2021-03-02 18:34 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/2019_DISK_ADD_issue.yaml
> +  name: "DiskAdded"
every alert will be available in UI, you don't need to have notifier for that.

2021-04-16 09:10 UTC, mishoyama approved these changes

2021-04-16 09:18 UTC, painhardcore approved these changes

2021-04-19 12:46 UTC, merged