[OBSDEF-5979] add apps with run-level for federation to start before iam
EMCECS/charts pull request #633
Opened 2021-02-22 22:52 UTC by bst525

## Purpose
[OBSDEF-5979](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-5979)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-02-22 23:22 UTC, eddiepavkovic reviewed
FYI.  the run-levels are only used in vSphere7 deployments where these apps are kicked off after we deploy the plugin.  
Can you please indicate what vSphere7 testing was done to ensure the feds start before iams

2021-02-22 23:22 UTC, eddiepavkovic commented on federation/templates/federation-app.yaml
> +  {{- if .Values.createApplicationResource }}
shouldn't be indented.

2021-02-22 23:22 UTC, eddiepavkovic commented on federation/templates/federation-app.yaml
> +  name: "federation"
```suggestion
  name: "objectscale-cloud"
```

2021-02-23 15:30 UTC, eddiepavkovic requested changes
we need to discuss with iam/fed team if this is the correct approach.  run-levels are only tracked by `install-controller` which is used during initial vsphere7 deployment.  and used by graphql to install objectstores, supportassist and licensing.

2021-03-03 10:32 UTC, vgupta-mickey reviewed
I thought I are suppose to have a meeting on this to understand the sub-charts vs run-level?
run-level make sense when the install controller is installing the federation service as a main chart

2021-03-03 15:00 UTC, closed without merging