[OBSDEF-5316] - Keep support store secret unchanged if already exists
EMCECS/charts pull request #634
Opened 2021-02-23 08:42 UTC by fyang86

## Purpose
[OBSDEF-5316](https://jira.cec.lab.emc.com/browse/OBSDEF-5316)
When we helm upgrade a chart, randAlphaNum inside secret will always change, which caused support store 401 unauthorized error. So we need to keep it unchanged if the secret already exists.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
```
kubectl get secret supportassist-objectscale-store-secret -o yaml
apiVersion: v1
data:
  password: VmpGYWEyUXhXWGhpUm1SVllUSm9VRll3V2t0amJGSllaVWhrVkZKdGVERlhXSEJ6VlZaV1ZVMUVhejA9
  salt: Vm10a05GVXhXWGhUV0doWVlUSm9jbFZ1Y0hOV1JsWnpWbXh3VGxKdGVERlhXSEJ6VlZaV1ZVMUVhejA9
  username: YQ==
```
After helm upgrade:
```
kubectl get secret supportassist-objectscale-store-secret -o yaml
apiVersion: v1
data:
  password: VmpGYWEyUXhXWGhpUm1SVllUSm9VRll3V2t0amJGSllaVWhrVkZKdGVERlhXSEJ6VlZaV1ZVMUVhejA9
  salt: Vm10a05GVXhXWGhUV0doWVlUSm9jbFZ1Y0hOV1JsWnpWbXh3VGxKdGVERlhXSEJ6VlZaV1ZVMUVhejA9
  username: YQ==
```

2021-02-23 15:32 UTC, eddiepavkovic commented
@fyang86  - but no upgrade was done so how did the secret change?

2021-02-24 03:51 UTC, fyang86 commented
> @fyang86 - but no upgrade was done so how did the secret change?

@eddiepavkovic I found that the timestamp of support store secret is the same time when helm chart updated.
```
kubectl get secret supportassist-objectscale-store-secret -o yaml
apiVersion: v1
data:
  password: R21lT0g3V2cxYQ==
  salt: MGpGYW5VbHJJZA==
  username: SXc1V0I=
kind: Secret
...
...
    operation: Update
    time: "2021-02-23T00:12:32Z"
```
```
helm list
NAME                     	NAMESPACE                  	REVISION	UPDATED                                  	STATUS  	CHART                     	APP VERSION

supportassist-objectscale	dellemc-eddie-68-domain-c45	1348    	2021-02-23 00:12:31.917143124 +0000 UTC  	failed  	supportassist-2.0.67      	2.0.67     
```
find this on your environment, maybe helm upgrade was evoked by something else.
Anyhow, I think we should keep the secret unchanged if it is using randAlphaNum when we doing helm upgrade.

2021-03-03 04:31 UTC, eddiepavkovic commented
@fyang86 - maybe we haven't tested this but are we sure the secret is updated on an upgrade.  i guess it is and thats why we're seeing these issues.

what's weird is that prior to changing the base image of nginx we didn't see this issue.  again maybe because we never tested upgrade as much as we do now.

2021-03-03 04:34 UTC, eddiepavkovic commented
helm lint is broken: 
```
==> Linting supportassist
[ERROR] templates/: parse error at (supportassist/templates/supportassist-ese-store-secret.yaml:9): function "lookup" not defined

==> Linting decks-support-store
[ERROR] templates/: parse error at (decks-support-store/templates/support-store-secret.yaml:8): function "lookup" not defined
```

https://asd-ecs-jenkins.isus.emc.com/jenkins/job/monitoring-libs/job/objectscale-charts/job/bugfix-OBSDEF-5316-fix-helm-upgrade-change-randAlphaNum/1/console

2021-03-03 10:26 UTC, vgupta-mickey requested changes
Let’s understand the problem here. We can’t reuse the previous secrets all the time, what happens if we really want to change the secrets.
Let’s find out the root cause of this problem.
Every upgrade the secret will change because the templates get run every time.

2021-03-03 16:03 UTC, vgupta-mickey commented on decks-support-store/templates/support-store-secret.yaml
>  type: Opaque
add annotation and use pre-intsall and delete-policy
https://github.com/EMCECS/charts/blob/master/ecs-cluster/templates/initial-user-secret.yaml

2021-03-04 04:00 UTC, eddiepavkovic requested changes

2021-03-04 05:55 UTC, fyang86 commented on decks-support-store/templates/support-store-secret.yaml
>    namespace: {{.Release.Namespace}}
updated with adding hook, retested and it worked

2021-03-04 07:03 UTC, eddiepavkovic approved these changes
Excellent

2021-03-04 07:38 UTC, fyang86 commented
@eddiepavkovic @vgupta-mickey there might be another issue using hook, if we `helm delete` support assist chart, this secret won't be deleted until there's new support assist installed. Do we want to keep this secret even if the chart is deleted?

2021-03-04 11:41 UTC, vgupta-mickey approved these changes
it is ok to keep the secrets until the next installment.

2021-03-08 01:26 UTC, merged