[OBSDEF-5233] Storageserver configuration cleanup
EMCECS/charts pull request #638
Opened 2021-02-24 14:22 UTC by aga-va

Remove storagesrver configuration settings which are irrelevant, outdated and those which just repeat the default values. This is to make it possible to cleanup storageserver startup scripts, Object Scale operator code and to simplify maintenance and upgrades in the future.

2021-02-24 15:24 UTC, eddiepavkovic requested changes
vadim,  can we hold off on this change until build 68 is done.

2021-02-24 15:30 UTC, mishoyama approved these changes

2021-02-24 17:30 UTC, aga-va commented
> vadim, can we hold off on this change until build 68 is done.

No problems with this.

2021-02-25 23:57 UTC, eddiepavkovic approved these changes
ok

2021-03-03 17:48 UTC, merged