[OBSDEF-956] logging injector labels to dcm
EMCECS/charts pull request #667
Opened 2021-03-09 00:20 UTC by skripg

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-03-10 05:48 UTC, vazhem requested changes

2021-03-10 05:48 UTC, vazhem commented on dcm/templates/_helpers.tpl
> +app.kubernetes.io/namespace: "{{ .Release.Namespace }}"
to avoid duplication please add dependency on common-monitoring-lib (like here https://github.com/EMCECS/charts/blob/master/statefuldaemonset-operator/Chart.yaml#L13)

And use 'include' here instead of specifying exact labels.

```
{{ include "common-monitoring-lib.logging-inject-labels" . | indent 8 }}
```
to add needed labels (like here https://eos2git.cec.lab.emc.com/ECS/monitoring/blob/master/k8s/charts/fluxd/templates/deployment.yaml#L35).

Also you need to include 'log' emptydir volume and volume mount in your container.
```
  volumeMounts:
    - name: log
      mountPath: <path to your logs in container>
...
volumes:
  - name: log
     emptyDir: {}
```

2021-03-13 03:18 UTC, skripg commented on dcm/templates/_helpers.tpl
> +app.kubernetes.io/namespace: "{{ .Release.Namespace }}"
Thank you! updated the PR. only I do not see labels popup: 
```
Name:         ecs-manager-dcm-5d7944cbdc-lcc98
Namespace:    default
Priority:     0
Node:         minikube/10.247.102.238
Start Time:   Fri, 12 Mar 2021 18:52:26 -0800
Labels:       app.kubernetes.io/instance=ecs-manager
              app.kubernetes.io/name=dcm
              pod-template-hash=5d7944cbdc
Annotations:  <none>
```

2021-03-15 08:49 UTC, vazhem commented on dcm/templates/_helpers.tpl
> +app.kubernetes.io/namespace: "{{ .Release.Namespace }}"
if you test dcm charts separately - remember to run 'helm dep up ./dcm' to load the lib and pass '--set global.logging_injection_enabled=true' on deployment.
To see rendered template with labels:
`helm template ./dcm/ --set global.logging_injection_enabled=true`

If you deploy as part of objectscale-manager - you need to update dcm charts in the ./charts folder for objectscale-manager

2021-03-15 20:40 UTC, skripg commented on dcm/templates/_helpers.tpl
> +app.kubernetes.io/namespace: "{{ .Release.Namespace }}"
I deploy objectscale-manager. I see the labels only if I provide `-set global.logging_injection_enabled=true` to objectscale-manager.
 ```
Name:         ecs-manager-dcm-6c4df4445f-mhnv8
Namespace:    default
Priority:     0
Node:         minikube/10.247.102.238
Start Time:   Mon, 15 Mar 2021 13:32:14 -0700
Labels:       app.kubernetes.io/instance=ecs-manager
              app.kubernetes.io/name=dcm
              app.kubernetes.io/namespace=default
              objectscale.dellemc.com/logging-inject=true
              objectscale.dellemc.com/logging-inject-rsyslog=false
              objectscale.dellemc.com/logging-release-name=ecs-manager
              pod-template-hash=6c4df4445f
```

2021-03-16 00:17 UTC, skripg commented on dcm/templates/_helpers.tpl
> +app.kubernetes.io/namespace: "{{ .Release.Namespace }}"
local `make build` `make test` passes, while jenkins job fails with 
```
==> Linting dcm
[ERROR] templates/: template: dcm/templates/deployment.yaml:18:3: executing "dcm/templates/deployment.yaml" at <include "common-monitoring-lib.logging-inject-labels" .>: error calling include: template: no template "common-monitoring-lib.logging-inject-labels" associated with template "gotpl"
```  
Do I need to add `dcm/charts/common-monitoring-lib-3.7.0-1138.568c1868.tgz` to the PR ?

2021-03-16 06:28 UTC, vazhem commented on dcm/templates/_helpers.tpl
> +app.kubernetes.io/namespace: "{{ .Release.Namespace }}"
logging injection should work by default, so updated objectscale-manager values with needed vars, so that it can work for any subchart who will add logging integration later.

fix is right, it is correct to add dependency for the chart by running helm dep up.

2021-03-16 06:32 UTC, vazhem approved these changes

2021-03-16 22:28 UTC, abercj2 approved these changes

2021-03-16 22:43 UTC, sumithreddy commented on dcm/Chart.yaml
> +    version: 3.7.0-1146.a692701d # no_auto_change__monitoring_auto_change
@vazhem how we track the version across the dependencies?
I don't see any global values tracking the lib version and thus can be used across sub charts

2021-03-16 22:46 UTC, sumithreddy commented on dcm/templates/deployment.yaml
> +              mountPath: /opt/storageos/conf/dcm-log4j2.xml
@vazhem for modifying log configuration on fly.
Do we have to edit the config map  or the file at mount location?

2021-03-16 22:46 UTC, sumithreddy approved these changes
LGTM!

Just have few questions for @vazhem

2021-03-16 22:47 UTC, merged

2021-03-16 22:49 UTC, skripg commented on dcm/templates/_helpers.tpl
> +app.kubernetes.io/namespace: "{{ .Release.Namespace }}"
Thank you a lot!

2021-03-17 07:31 UTC, vazhem commented on dcm/templates/deployment.yaml
> +              mountPath: /opt/storageos/conf/dcm-log4j2.xml
configmap

2021-03-17 07:32 UTC, vazhem commented on dcm/Chart.yaml
> +    version: 3.7.0-1146.a692701d # no_auto_change__monitoring_auto_change
```
# no_auto_change__monitoring_auto_change
```

this is special comment which causes autoupdate of monitoring dependencies. Will update autoupdate script to update dcm chart too