[OBSDEF-6043] federation add atlas store
EMCECS/charts pull request #707
Opened 2021-04-06 21:07 UTC by bst525

## Purpose
[OBSDEF-6043](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6043)
Adds the atlas store to federation charts

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-04-07 00:19 UTC, eddiepavkovic requested changes

2021-04-07 00:19 UTC, eddiepavkovic commented on federation/templates/atlas_v1beta1_fedcluster.yaml
> +  replicas: {{ .Values.atlas.replicaCount }}
missing `imagePullSecrets` required to be able to pull docker images from private registries: https://github.com/EMCECS/charts/blob/6943ed6856ed463408545312174416a538977b94/dcm/templates/atlas_v1beta1_dcmcluster.yaml#L9-L11

2021-04-07 00:19 UTC, eddiepavkovic commented on federation/values.yaml
> +    tag: v1.1.2
needs to be the latest atlas. 

```suggestion
    tag: v1.1.3
```

2021-04-07 13:27 UTC, bst525 commented on federation/templates/atlas_v1beta1_fedcluster.yaml
> +  replicas: {{ .Values.atlas.replicaCount }}
Done.

2021-04-07 13:29 UTC, bst525 commented on federation/values.yaml
> +    tag: v1.1.2
Checked iamsvc - value is 1.1.3 (no longer v1).  Made the change here to match.

2021-04-07 18:31 UTC, SeemaTahaliyani approved these changes

2021-04-08 07:17 UTC, fedor-chemashkin commented on federation/values.yaml
> +  replicaCount: 3
For small and micro profiles we use 1 atlas replica for ObjectStore

2021-04-08 12:52 UTC, bst525 commented on federation/values.yaml
> +  replicaCount: 3
@fedor-chemashkin Automation has been updated to use replicaCount=1.  this is same design used by IAM.

2021-04-08 12:57 UTC, fedor-chemashkin commented on federation/values.yaml
> +  replicaCount: 3
From the user perspective, default charts installation will use 3 replicas even for small profiles

2021-04-08 13:09 UTC, bst525 commented on federation/values.yaml
> +  replicaCount: 3
@fedor-chemashkin I have updated it to 1

2021-04-08 16:18 UTC, eddiepavkovic approved these changes
ok

2021-04-08 16:22 UTC, merged