[OBSDEF-6862] RFw comments to assign image tags and chart versions during automated release
EMCECS/charts pull request #724
Opened 2021-04-16 18:22 UTC by nikolay-t

As per our agreement, release process will benefit from using development image tags and chart versions.
This PR adds required comment markers that will be processed and tags/versions from version slice will be used.

https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-ci-vsph7-large/411/ is example of successful installation with image tags inserted in charts.

2021-04-16 18:26 UTC, eddiepavkovic requested changes
why are we updating each individual tag vs the global tag.

2021-04-16 18:30 UTC, nikolay-t commented
> 
> 
> why are we updating each individual tag vs the global tag.

Because we want automation to insert specific image tag from version slice.

2021-04-16 18:35 UTC, eddiepavkovic commented on decks/values.yaml
> +  tag: # rfw-update-this decks-image
why are we setting this value vs the one above at line 23.

how does helm upgrades work?  will it force pull in from this value vs the one at line 
https://github.com/EMCECS/charts/blob/5ab55965e4127d8b63a51cce0c486774386b6e0b/decks/values.yaml#L22-L23

2021-04-16 18:35 UTC, eddiepavkovic commented on decks/values.yaml
> +  tag: # rfw-update-this decks-image
The other problem i see is that these tags now have to match to what's generated in the manifest and ci builds and the charts.

Can this tag be based on the component and not the image value:
```
  tag: # rfw-update-this decks-image
```

can we change this to be 
```
    tag: # rfw-update-this
```

Then when the code is processing this values.yaml it knows the chart & component as decks and updates accordingly.  oh maybe not.

2021-04-16 18:46 UTC, nikolay-t commented on decks/values.yaml
> +  tag: # rfw-update-this decks-image
I will need to verify upgrade case. Look, for now - until we start calling "make resolve-versions" these markers are totally harmless, even when this PR is merged. They will only be applied after first "make resolve-versions", which we don't plan to enable or require without proper testing. 

We plan to make two internal releases without pushing to master. With two releases, we will have a chance to try upgrade case.

2021-04-19 15:22 UTC, nikolay-t commented on decks/values.yaml
> +  tag: # rfw-update-this decks-image
@eddiepavkovic I made changes for values.yaml in ecs-cluster - markers now set to update 'default' tag and image tags will be inserted only if they differ from component version for individual images. It is because developers use "--set tag=..." for ecs-cluster. I don't see any other reasons to change markers - they should be in places where image tag is specified, not the default tag. The default tag just used to override empty/unset "image.tag" values.

For concerns about 'upgrade' case: we have several places where fixed image versions are set (i.e. atlas image in dcm chart, zookeeper chart, etc). This surely works in upgrade. Proposed change is the same approach.

New test is now running. Do you have any concerns about merge of this PR? Please share, we would like to merge it soon.

2021-04-19 17:03 UTC, aoberezin approved these changes

2021-04-20 04:10 UTC, eddiepavkovic commented
need to merge from master to pick up all the helm lint and yamllint fixes.

2021-04-20 04:25 UTC, eddiepavkovic commented
Changes look ok.  i am concerned about hardcoding the # rfw comments and getting the syntax right.  we'll need "audit" or "lint" tools that'll ensure what the component versions are setting match to whats in the charts.

2021-04-20 04:28 UTC, eddiepavkovic commented
Also we missed the following for objectscale & objectstore healthchecks:

1. https://github.com/EMCECS/charts/blob/bf574b29506a00f053107734327c23050bbeedc0/objectscale-manager/values.yaml#L234-L239
2. https://github.com/EMCECS/charts/blob/4221736bc91d10965dd759c2d5b3a171511ed361/objectscale-manager/templates/objectscale-manager-app-configmap.yaml#L22-L29
3. https://github.com/EMCECS/charts/blob/4221736bc91d10965dd759c2d5b3a171511ed361/ecs-cluster/templates/objectstore-app-configmap.yaml#L29-L43
4.

2021-04-20 11:36 UTC, nikolay-t commented
@eddiepavkovic for your questions,

> need to merge from master to pick up all the helm lint and yamllint fixes.

PR is updated

> we'll need "audit" or "lint" tools that'll ensure what the component versions are setting match to whats in the charts.

For now this is covered by automated testing. Every objectscale-master-acceptance will set default tag values (where applicable) to non-existing release and run `make resolve-versions`. This will fail the test if any image is not tagged correctly. 

> Also we missed the following for objectscale & objectstore healthchecks. will the values.yaml settings take precendence here?

Settings in ecs-cluster/templates/objectstore-app-configmap.yaml are fine because healthChecks.connectivity.image.tag in set in its values.yaml.

objectscale-manager/templates/objectscale-manager-app-configmap.yaml needed fix, which is:

https://github.com/EMCECS/charts/pull/724/files/90354aad4255a9dea052d7f9545a552afc7adfa2..77b3ee13e2efd125a71610f848c9de8f7b757900

I also checked other places for usage of {{.Values.tag}} for image tag and didn't find more issues.

2021-04-20 20:15 UTC, eddiepavkovic approved these changes
lgmt,  thanks for making the updates and the thorough responses.

2021-04-21 10:48 UTC, merged