update charts for license capacity
EMCECS/charts pull request #736
Opened 2021-04-20 18:58 UTC by SarahAFochs

## Purpose
[OBSDEF-1909](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-1909)
Add the sub charts under objectscale manager to generate the report for license data.

Relates to healthcheck pr: [OBSDEF-1909] Check licensed capacity vs usage](https://eos2git.cec.lab.emc.com/ECS/objectscale-healthchecks/pull/35)

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

2021-04-20 23:58 UTC, vgupta-mickey requested changes
Add configurable options in values.yaml

2021-04-20 23:58 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +      - name: license
License-usage

2021-04-20 23:58 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +        schedule: "0 */6 * * *"
Are you planning to run every 6 hours ?

2021-04-20 23:58 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +        schedule: "0 */6 * * *"
Schedule should be configurable as per the discussion.

2021-04-20 23:58 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +        schedule: "0 */6 * * *"
Add disabled flag as well in case we need to disable this

2021-04-20 23:58 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +        serviceaccount: {{ .Release.Name }}-healthchecks
Service account should be specific to the license usage

2021-04-21 14:49 UTC, SarahAFochs commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +        serviceaccount: {{ .Release.Name }}-healthchecks
should i also change [this ](https://github.com/EMCECS/charts/blob/632fac46fed9cab5764d3dbf2e10b6b0d7cfb10a/objectscale-manager/templates/objectscale-manager-app-configmap.yaml#L32)entry?

2021-04-21 14:50 UTC, SarahAFochs commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +        schedule: "0 */6 * * *"
yes, as per discussion

2021-04-21 16:48 UTC, eddiepavkovic requested changes
@SarahAFochs - lets work together to integrate vinods changes so that we're not going back and forth on comments.

2021-04-23 11:21 UTC, vgupta-mickey commented on objectscale-manager/templates/telemetry-rbac.yaml
> +      - '*'
need to make it restrictive instead of wild card permissions.

2021-04-23 14:34 UTC, eddiepavkovic requested changes

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/telemetry-rbac.yaml
> +  name: {{ .Release.Name }}-license
```suggestion
  name: {{ .Release.Name }}-license-usage
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/telemetry-rbac.yaml
> +  name: {{ .Release.Name }}-license
```suggestion
  name: {{ .Release.Name }}-license-usage
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/telemetry-rbac.yaml
> +---
Replace with this:
```
rules:
- apiGroups:
  - decks.ecs.dellemc.com
  resources:
  - licenses
  verbs:
  - get
  - update
  - list
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  - secrets
  verbs:
  - get
  - list
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/telemetry-rbac.yaml
> +---
add new line here

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/telemetry-rbac.yaml
> +  name: {{ .Release.Name }}-license
```suggestion
  name: {{ .Release.Name }}-license-usage
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/telemetry-rbac.yaml
> +    name: {{ .Release.Name }}-license
```suggestion
    name: {{ .Release.Name }}-license-usage
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/values.yaml
> +      repository: objectscale-license
```suggestion
      repository: objectscale-license-usage
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          schedule: {{ default "0 */6 * * *" .Values.healthChecks.license.schedule }}
```suggestion
          schedule: {{ default "0 */6 * * *" .Values.healthChecks.license.schedule | quote }}
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/values.yaml
> +  license:
```suggestion
  licenseUsage:
```

2021-04-23 14:34 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          container: {{.Values.global.registry}}/objectscale-license:{{ default .Values.tag .Values.healthChecks.license.image.tag}}
```suggestion
          container: {{.Values.global.registry}}/{{ .Values.healthChecks.licenseUsage.image.repository:{{ default .Values.tag .Values.healthChecks.license.image.tag}}
```

2021-04-25 17:37 UTC, eddiepavkovic approved these changes
ok lets fix the conflicts so we can merge.

2021-04-26 13:01 UTC, vgupta-mickey requested changes

2021-04-26 13:01 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          serviceaccount: {{ .Release.Name }}-license
license-usage

2021-04-26 13:01 UTC, vgupta-mickey commented on objectscale-manager/values.yaml
> +      schedule: "0 */6 * * *"
should be at image level

2021-04-26 13:01 UTC, vgupta-mickey commented on objectscale-manager/values.yaml
> +      disabled: false
should be at image level

2021-04-26 19:01 UTC, youminhan approved these changes
Just curious that why we are adding `get-pip.py` to the charts.

2021-04-26 19:19 UTC, vgupta-mickey requested changes
Sarah, Please fix my comments otherwise the release will break.

2021-04-26 19:19 UTC, vgupta-mickey commented on objectscale-manager/templates/telemetry-rbac.yaml
> +  name: { { .Release.Name } }-license-usage
```suggestion
  name: { { .Release.Namespace } }-license-usage
```

2021-04-26 19:19 UTC, vgupta-mickey commented on objectscale-manager/templates/telemetry-rbac.yaml
> +  name: { { .Release.Name } }-license-usage
```suggestion
  name: { { .Release.Namespace } }-license-usage
```

2021-04-26 19:19 UTC, vgupta-mickey commented on objectscale-manager/templates/telemetry-rbac.yaml
> +  name: { { .Release.Name } }-license
```suggestion
  name: { { .Release.Namespace } }-license
```

2021-04-26 19:22 UTC, vgupta-mickey reviewed
You need to merge from master before check-ins.

2021-04-26 19:40 UTC, vgupta-mickey approved these changes

2021-04-27 02:32 UTC, tmarcu requested changes
we're committing files that don't need to be committed

2021-04-27 02:32 UTC, tmarcu commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          disabled: {{ default false .Values.healthChecks.inventory.disabled}}
This isn't required to be added, it's _not_ disabled by default, and if you want to disable you can add `disabled: true`

2021-04-27 02:32 UTC, tmarcu commented on temp_package/yaml/kahm.yaml
> +---
temp_package should not be commited

2021-04-27 03:47 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          disabled: {{ default false .Values.healthChecks.inventory.disabled}}
this is a helm-ism.   if we leave it at true then you can't update.  or something like tha... we ran into this earlier this year with supportassist,  it was an odd boolean ism with helm.

2021-04-27 03:47 UTC, eddiepavkovic commented on log/deploy-objectscale-210426.log
> +21.04.26 14:56:12 : Starting deployment of ObjectScale
don't merge this file.  this is a run from your deployment script.  do a git rm log so that its no longer being merged.

2021-04-27 17:41 UTC, eddiepavkovic approved these changes

2021-04-27 18:14 UTC, tmarcu approved these changes
:ok: :100: :1st_place_medal:

2021-04-27 18:16 UTC, merged