Feature 0.71.2 add prvg rsyslog support tmp test
EMCECS/charts pull request #738
Opened 2021-04-21 12:29 UTC by CraneShiEMC

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-04-21 15:26 UTC, eddiepavkovic requested changes
Crane,  it seems you branch is out of date.  can you run this in your branch:

```
git pull origin master 
``` 
some of the files are already in master.

2021-04-22 10:31 UTC, CraneShiEMC commented
> Crane, it seems you branch is out of date. can you run this in your branch:
> 
> ```
> git pull origin master 
> ```
> 
> some of the files are already in master.

@eddiepavkovic Now, I have merged latest master commits.

2021-04-26 15:58 UTC, eddiepavkovic commented on ecs-cluster/templates/ecs-cluster.yaml
> +      objectscale.dellemc.com/logging-release-name: "{{ .Release.Name }}"
@vazhem - should this be a macro from `common-libs`?

2021-04-26 15:58 UTC, eddiepavkovic commented on zookeeper-operator/values.yaml
> +  tag: 0.2.9-173-5c86f53 # rfw-update-this zookeeper-operator-docker-image
this should be `0.2.10...`

2021-04-27 05:31 UTC, eddiepavkovic approved these changes
lgmt

2021-04-27 06:12 UTC, realAaronWu approved these changes

2021-04-27 08:59 UTC, vazhem commented on ecs-cluster/templates/ecs-cluster.yaml
> +      objectscale.dellemc.com/logging-release-name: "{{ .Release.Name }}"
add dependency on monitoring lib and use
```
{{ include "common-monitoring-lib.logging-inject-labels" . | indent 8 }}
```
(with correct indentation)

2021-04-27 09:09 UTC, fedor-chemashkin commented on ecs-cluster/templates/ecs-cluster.yaml
> +      objectscale.dellemc.com/logging-release-name: "{{ .Release.Name }}"
We shouldn't put these labels here

2021-04-27 14:49 UTC, merged