charts changes required for Telemetry collections and uploads
EMCECS/charts pull request #740
Opened 2021-04-21 14:37 UTC by vgupta-mickey

## Purpose
[OBSDEF-1830](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-1830)
The health framework will be used generate telemetry reports at objectscale-manager level and the same will be used to upload the reports at support-assist application level.
The customer and charts will provide the option to modify the followings:
Enable or Disable reports
Schedule
By using the health check framework, we can run these reports on demand basis in additon to the periodic reports.

## PR checklist
- [ x] make test passed
- [ x] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-04-21 16:38 UTC, eddiepavkovic requested changes

2021-04-21 16:40 UTC, eddiepavkovic commented on objectscale-manager/values.yaml
> +  healthReport:
```suggestion
  health:
```

2021-04-22 19:32 UTC, eddiepavkovic approved these changes

2021-04-22 21:14 UTC, youminhan approved these changes

2021-04-23 14:39 UTC, eddiepavkovic requested changes

2021-04-23 14:39 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          container: {{.Values.global.registry}}/objectscale-inventory:{{default .Values.tag .Values.healthChecks.inventory.image.tag}}
```suggestion
          container: {{.Values.global.registry}}/{{ .Values.healthChecks.inventory.image.repository:{{default .Values.tag .Values.healthChecks.inventory.image.tag}}
```

2021-04-23 14:39 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          container: {{.Values.global.registry}}/objectscale-capacity:{{default .Values.tag .Values.healthChecks.capacity.image.tag}}
Please get the repo name from values file

2021-04-23 14:39 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          container: {{.Values.global.registry}}/objectscale-performance:{{default .Values.tag .Values.healthChecks.performance.image.tag}}
get repo name from values file.

2021-04-23 14:39 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          container: {{.Values.global.registry}}/objectscale-health:{{default .Values.tag .Values.healthChecks.health.image.tag}}
get repo name from values file.

2021-04-23 14:54 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          container: {{.Values.global.registry}}/objectscale-performance:{{default .Values.tag .Values.healthChecks.performance.image.tag}}
yep, cut and paste from healthcheck pre-update.

2021-04-23 21:35 UTC, NguyenMartin approved these changes

2021-04-23 21:36 UTC, merged