[OBSDEF-7331]Feature add sp for pravega
EMCECS/charts pull request #750
Opened 2021-04-27 08:19 UTC by realAaronWu

## Purpose
[OBSDEF-7331](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7331)
add pravega bookie service procedure support.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-04-29 16:45 UTC, eddiepavkovic reviewed
this looks out of date.  can you merge from master.

2021-05-05 15:08 UTC, BassinD requested changes

2021-05-05 15:08 UTC, BassinD commented on ecs-cluster/templates/ecs-cluster.yaml
> +      objectscale.dellemc.com/sp-integrated-recovery-status-probe-exec: "bk_sp.sh_-t_precheck_-o_600"
I see a problem with splitting the label value to the command because the script name `bk_sp.sh` contains the `_` separator.
Let's stay `_` symbol as a separator, but add some limitations to the script name: it shouldn't contain `_` in the name.

2021-05-06 01:06 UTC, realAaronWu commented on ecs-cluster/templates/ecs-cluster.yaml
> +      objectscale.dellemc.com/sp-integrated-recovery-status-probe-exec: "bk_sp.sh_-t_precheck_-o_600"
thanks, will do.

2021-05-06 07:03 UTC, realAaronWu commented
Close this pr since branch is too old.

2021-05-06 07:03 UTC, closed without merging