[OBSDEF-885] tls configuration for georeceiver
EMCECS/charts pull request #751
Opened 2021-04-27 16:15 UTC by xuz10

## Purpose
[OBSDEF-885](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-885)
Added tls section in chart for operator to pick up for generate CA for georeceiver.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-04-28 05:56 UTC, rhythmhavoc888 approved these changes

2021-04-28 06:21 UTC, eddiepavkovic requested changes
Is this required for 72?    @Bjohnson131 @nikolay-t

2021-04-28 06:33 UTC, rhythmhavoc888 commented
> Is this required for 72? @Bjohnson131 @nikolay-t

Not a must for 72

2021-05-07 04:11 UTC, mmll approved these changes

2021-05-07 04:27 UTC, eddiepavkovic approved these changes
ok

2021-05-07 05:52 UTC, merged