[OBSDEF-7331] add sp for pravega/bookkeeper
EMCECS/charts pull request #762
Opened 2021-05-06 07:05 UTC by realAaronWu

## Purpose
[OBSDEF-7331](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7331)
_List the changes for this PR_
add pravega bookie service procedure support.
## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-05-06 07:25 UTC, BassinD requested changes
Will you add sp operator labels to the pravega pods (https://github.com/EMCECS/charts/pull/762/files#diff-2ec929c087c81c76635acaa9a219b4b26385647522dfae309ebc5832226d8f3eR316) ?

2021-05-06 07:25 UTC, BassinD commented on ecs-cluster/templates/ecs-cluster.yaml
> +      objectscale.dellemc.com/sp-integrated-pmm: "true"
1. You can use the `sp-integrated-all: "true"` label instead of 3 above.
2. The _common-lib/teplates/_sp_operator_labels.yaml_ file already contains templates with sp operator labels. 
Usage example: 
```
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
{{ include "common-lib.labels-sp-integrated-initiate-decommission-script" (dict "script" "/my_script") | indent 8}}
```
3.  It's not in master yet, but you should add an `vsphere-emm-integrated: "true"` annotation to prevent auto pod removal by VSphere. Defined [here](https://github.com/EMCECS/charts/pull/759/files#diff-b58600f32ca61c5becb8945bc516b3f8a2276d8c3409603d112258cba4f744b1R79)

2021-05-06 10:48 UTC, BassinD commented on ecs-cluster/templates/ecs-cluster.yaml
> +      vsphere-emm-integrated: "true"
It should be an annotation. Discussed it in IM.

2021-05-07 08:40 UTC, BassinD commented on ecs-cluster/templates/ecs-cluster.yaml
>        options:
Seems you forgot to add `vsphere-emm-integrated: "true"` annotation into the pravega pods.

2021-05-07 11:36 UTC, BassinD approved these changes

2021-05-07 11:37 UTC, BassinD commented on ecs-cluster/templates/ecs-cluster.yaml
>        options:
These changes will be inluced with pravega-operator in another PR

2021-05-07 12:08 UTC, antonbassin approved these changes

2021-05-07 12:13 UTC, merged