[OBSDEF-8290] KAHM event rules for SP operator events
EMCECS/charts pull request #782
Opened 2021-05-14 15:00 UTC by BassinD

## Purpose
[OBSDEF-8290](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8290)
KAHM event rules for SP operator events described here: https://confluence.cec.lab.emc.com/display/OBJSCALE/ObjectScale+Service+Procedure+Operator+KAHM+Events

Relates to the changes in this PR: https://eos2git.cec.lab.emc.com/ECS/ecs-flex-operator/pull/390

## PR checklist
- [x] make test passed
- [x] make build passed
- [x] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
Tested only k8s events.
Deployed custom [image](https://asd-ecs-jenkins.isus.emc.com/jenkins/job/operator-custom-build/680/), initiated DR with error and checked k8s events:
```
kubectl get events  --sort-by=.metadata.creationTimestamp | grep application/objectscale

LAST SEEN   TYPE      REASON                                   OBJECT                                                 MESSAGE
51m         Normal    Found unhealthy PVC                      application/objectscale-manager                           Found unhealthy PVC handlig by SP operator: index-ecs-cluster-bk-bookie-0
51m         Error     Error occurred during disk replacement   application/objectscale-manager                           Something went wrong during disk replacement: pods "ecs-cluster-bk-bookie-0" is forbidden: User "system:serviceaccount:default:objectscale-operator" cannot create resource "pods/exec" in API group "" in the namespace "default"
7m4s        Normal    Found unhealthy PVC                      application/objectscale-manager                           Found unhealthy PVC handlig by SP operator: index-ecs-cluster-bk-bookie-0
6m25s       Normal    Recovery started                         application/objectscale-manager                           Started data recovery of the ecs-cluster-bk-bookie-0 application
5m37s       Normal    Pod for failed PVC removed               application/objectscale-manager                           Pod ecs-cluster-bk-bookie-0 used unhealthy PVC was removed
5m37s       Normal    Failed PVC removed                       application/objectscale-manager                           Unhealthy PVC index-ecs-cluster-bk-bookie-0 was removed
5m37s       Normal    Recovery finished                        application/objectscale-manager                           Finished data recovery of the ecs-cluster-bk-bookie-0 application
5m37s       Normal    Disk Replacement started                 application/objectscale-manager                           Starting replacement of failed PVCs index-ecs-cluster-bk-bookie-0
5m7s        Normal    Disk Replacement finished                application/objectscale-manager                           Finished replacement of failed PVCs index-ecs-cluster-bk-bookie-0
```

2021-05-14 15:35 UTC, eddiepavkovic requested changes

2021-05-14 15:35 UTC, eddiepavkovic commented on objectscale-manager/alerts/issues/OBJSC-SP-0001_RECOVERY_STARTED_issue.yaml
> +- description: "Object Scale service procedure started Recovery Process"
```suggestion
- description: "ObjectScale service procedure started Recovery Process"
```
ObjectScale is one word no space.  thats the official product name.  please fix in all descriptions.

2021-05-14 15:59 UTC, kanchr2 commented on objectscale-manager/alerts/issues/OBJSC-SP-2052_PMM_NO_FREE_CAPACITY_issue.yaml
> +    - objectscale-supportassist-ese
We might not need to send all the alerts to CLM. Better go over with Bob(Robert Kenney) so that he can help in identifying the right Symptom ID which we need to send to CLM

2021-05-14 20:52 UTC, vgupta-mickey requested changes

2021-05-17 11:27 UTC, BassinD commented on objectscale-manager/alerts/issues/OBJSC-SP-0001_RECOVERY_STARTED_issue.yaml
> +    - matchon:
Do we need event rules for 'Normal' events at all or should they have another implementation?
[KAHM Desing](https://confluence.cec.lab.emc.com/display/OBJSCALE/KAHM+managing+application+issues) has an example with Normal event and it contains eventRule in the Config map.
Also ecs-cluster has a few alerts with the 'Normal' severity (e.g. https://github.com/EMCECS/charts/blob/master/ecs-cluster/alerts/issues/1325_BTREE_DISK_SR_THRESHOLD_EXCEEDED_issue.yaml#L7)

2021-05-17 11:29 UTC, BassinD commented on objectscale-manager/alerts/issues/OBJSC-SP-2052_PMM_NO_FREE_CAPACITY_issue.yaml
> +    - objectscale-supportassist-ese
Do we have a guide with rules which alerts should have notifiers?
I added it because most of the [ecs-cluster alerts](https://github.com/EMCECS/charts/tree/master/ecs-cluster/alerts/issues) have it.

2021-05-17 12:39 UTC, vgupta-mickey requested changes
If you want we can setup a meeting on this but it seems too many issues are created and we don't need all of them. We can combine most of them into 2-3 issues.

2021-05-17 12:39 UTC, vgupta-mickey commented on objectscale-manager/alerts/issues/OBJSC-SP-0001_RECOVERY_STARTED_issue.yaml
> +    - matchon:
The idea is that we should define an unique symptomID for an  issue. An issue can start with severity/type=Warning and can get elevated to Error/Critical. They all can be reported with the same SymptomID. Also, when the issue is resolved , the issue can be cleared by using the same SymptomID with severity/Type=Normal.

So if you want to report an informational event to Dell EMC back-end system which is not an issue, then it should be defined under the issueRules. Instead it should be defined under the rules:

2021-05-17 12:39 UTC, vgupta-mickey commented on objectscale-manager/alerts/issues/OBJSC-SP-0001_RECOVERY_STARTED_issue.yaml
> +    - matchon:
regarding the ECSCluster example, you have given, the application developer has created one SymptomID per severity type which is not desirable. We should have one SymtpomID per issue, instead of one SymtpomID per severity unless you have a different requirememt in your mind.
The above rule should have been like this:
- description: "Capacity free-up throughput is too slow to catch up with system metadata garbage collection"
  name: "BTREE_DISK_SR_THRESHOLD_EXCEEDED"
  defaultAutoClearTimeOut: 60
  issueCategory: Auto
  matchOnList:
    - matchon:
        - label: SymptomID
          value: 1325
  notifiers:
    - objectscale-supportassist-ese
```




```

2021-05-17 12:39 UTC, vgupta-mickey commented on objectscale-manager/alerts/issues/OBJSC-SP-0001_RECOVERY_STARTED_issue.yaml
> +    - matchon:
In this case when the issue is cleared. A new event should get generated with SymptomID=1325 and Type=Normal

2021-05-17 12:39 UTC, vgupta-mickey commented on objectscale-manager/alerts/issues/OBJSC-SP-0051_RECOVERY_IN_PROGRESS_issue.yaml
> +          value: OBJSC-SP-0051
why not combine SP-0002 and SP-0051 in one rule.

2021-05-17 12:39 UTC, vgupta-mickey commented on objectscale-manager/alerts/issues/OBJSC-SP-1001_DISK_REPLACEMENT_STARTED_issue.yaml
> +    - matchon:
All Disk Replacement rules must be combined into one rule. Keep in mind, a Normal event won't create an issue.

Did you verify that the issues are getting created and cleared as per the requirement?

2021-05-17 13:42 UTC, BassinD commented on objectscale-manager/alerts/issues/OBJSC-SP-1001_DISK_REPLACEMENT_STARTED_issue.yaml
> +    - matchon:
No, I verified only events in the `k8s events` pool. Do we have a guide on how to verify the issues? (Preferably to do it without UI)

2021-05-17 13:42 UTC, BassinD commented
Closing to make breaking changes in the rules.

2021-05-25 14:12 UTC, vgupta-mickey approved these changes

2021-05-25 15:33 UTC, eddiepavkovic approved these changes
ok

2021-05-25 16:43 UTC, BassinD commented on objectscale-manager/alerts/issues/OBJSC-SP-0001_RECOVERY_STARTED_issue.yaml
> +    - objectscale-supportassist-ese
I'll discuss it with Bob(Robert Kenney) and add it in the future if required.

2021-05-25 16:43 UTC, BassinD commented on objectscale-manager/alerts/issues/OBJSC-SP-0002_RECOVERY_FINISHED_issue.yaml
> +    - objectscale-supportassist-ese
It's outdated already.

2021-05-25 16:44 UTC, merged