[OBSDEF-7816] cm topology alert
EMCECS/charts pull request #788
Opened 2021-05-19 03:43 UTC by xuh23

Add 12006_FAILED_TIER, 12007_FAILED_FD, and 12008_PRAVEGA_THRESHOLD_EXCEEDED_WARNING

2021-05-20 11:29 UTC, victor-polyansky commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  defaultAutoClearTimeOut: 180
These alerts are raised with `AlertHandler.raiseAlert()` that has filtering of duplicated alerts. Did you check that 180 sec clear timeout is enough here?

2021-05-20 18:16 UTC, eddiepavkovic requested changes

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +- description: "If tier is down or can not be written to"
what is a "tier" here?  storage tier?  if so reword it as:
```suggestion
- description: "Storage tier is not available or degraded"
```

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  name: "FAILED_TIER"
Name should be clear what this is about.

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +        # WARNING
Remove this... the symptomID will raise the issue as a warning and another 13000 event as "Normal would clear the issue.

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13001_FAILED_FD_issue.yaml
> +- description: "If FD is down or can not be written to"
```suggestion
- description: "Fault Domain is not available or degraded"
```

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13001_FAILED_FD_issue.yaml
> +  name: "FAILED_FD"
```suggestion
  name: "Fault Domain unavailable"
```

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13001_FAILED_FD_issue.yaml
> +        # WARNING
Remove

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13002_PRAVEGA_THRESHOLD_EXCEEDED_WARNING_issue.yaml
> +- description: "If Pravega warning limit exceeded"
What pravega threshold is exceeded.

```suggestion
- description: "Pravega threshold exceeded"
```
The "warning" will already be listed in the issue in the gui.

2021-05-20 18:16 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13002_PRAVEGA_THRESHOLD_EXCEEDED_WARNING_issue.yaml
> +        # WARNING
Remove #WARNING  the SymptomID posted should indicated if its a warning or error.

2021-05-21 02:41 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  defaultAutoClearTimeOut: 180
SsSelector.Refresher.refreshSsList refreshes every 3 minutes. Therefore, if the alert was raised, but no longer be raised
 3 minutes later, it should be regarded as timeout.

2021-05-21 07:31 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +- description: "If tier is down or can not be written to"
Done

2021-05-21 07:32 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  name: "FAILED_TIER"
Done

2021-05-21 07:32 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +        # WARNING
Done

2021-05-21 07:32 UTC, xuh23 commented on ecs-cluster/alerts/issues/13001_FAILED_FD_issue.yaml
> +- description: "If FD is down or can not be written to"
Done

2021-05-21 07:32 UTC, xuh23 commented on ecs-cluster/alerts/issues/13001_FAILED_FD_issue.yaml
> +  name: "FAILED_FD"
Done

2021-05-21 07:32 UTC, xuh23 commented on ecs-cluster/alerts/issues/13001_FAILED_FD_issue.yaml
> +        # WARNING
Done

2021-05-21 07:32 UTC, xuh23 commented on ecs-cluster/alerts/issues/13002_PRAVEGA_THRESHOLD_EXCEEDED_WARNING_issue.yaml
> +- description: "If Pravega warning limit exceeded"
Done

2021-05-21 07:32 UTC, xuh23 commented on ecs-cluster/alerts/issues/13002_PRAVEGA_THRESHOLD_EXCEEDED_WARNING_issue.yaml
> +        # WARNING
Done

2021-05-21 08:18 UTC, victor-polyansky commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  defaultAutoClearTimeOut: 180
Just wanted to ensure that in case when tier is down during several refreshes, KAHM gets all the events with 3 minutes interval. If it's so, then it's ok to have 3 min timeout.

2021-05-24 08:29 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +          value: 13000
Is "OBJSC-MON-13000" appropriate in this case?

2021-05-24 09:21 UTC, victor-polyansky commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +          value: 13000
@kanchr2 @xuh23 These are object store alerts sent to KAHM by eventsvc. It is planned that the eventsvc will add common prefix to all the alerts in terms of https://jira.cec.lab.emc.com/browse/OBSDEF-7219 and https://jira.cec.lab.emc.com/browse/OBSDEF-7220
SymptomID should be left as is for now.

2021-05-24 10:17 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  defaultAutoClearTimeOut: 180
Got it. It's so for now.

2021-05-24 10:21 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +          value: 13000
Thank you very much. I'll keep it unchanged.

2021-05-24 14:09 UTC, kanchr2 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +          value: 13000
But in this issues yaml file you need to mention the exact symptom ID(Here for Ex: OBJSC-CM-13000) if not it will not list in the Issues tab and may not send to CLM. @vgupta-mickey is my understanding right.

2021-05-24 16:49 UTC, victor-polyansky commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +          value: 13000
@kanchr2 We are going to update symptom IDs in all issue yamls along with changes in eventsvc

2021-05-25 12:52 UTC, kanchr2 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +          value: 13000
thank you

2021-05-25 14:43 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  defaultAutoClearTimeOut: 180
defaultAutoClearTime is in minutes. So in your case, you are setting the defaultAutoClearTimeout=180 which is 180 minutes.

2021-05-25 14:56 UTC, vgupta-mickey requested changes

2021-05-25 14:56 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13001_FAULT_DOMAIN_UNAVAILABLE_issue.yaml
> +  defaultAutoClearTimeOut: 180
this is in minutes.. so if your intention is  180 minutes, then it is fine.

2021-05-25 14:56 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13002_PRAVEGA_THRESHOLD_EXCEEDED_issue.yaml
> +  defaultAutoClearTimeOut: 180
same

2021-05-25 14:56 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13000_STORAGE_TIER_UNAVAILABLE_issue.yaml
> +  defaultAutoClearTimeOut: 180
same

2021-05-27 06:08 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_STORAGE_TIER_UNAVAILABLE_issue.yaml
> +  defaultAutoClearTimeOut: 180
Done

2021-05-27 06:08 UTC, xuh23 commented on ecs-cluster/alerts/issues/13002_PRAVEGA_THRESHOLD_EXCEEDED_issue.yaml
> +  defaultAutoClearTimeOut: 180
Done

2021-05-27 06:08 UTC, xuh23 commented on ecs-cluster/alerts/issues/13001_FAULT_DOMAIN_UNAVAILABLE_issue.yaml
> +  defaultAutoClearTimeOut: 180
Done

2021-05-27 06:11 UTC, xuh23 commented on ecs-cluster/alerts/issues/13000_FAILED_TIER_issue.yaml
> +  defaultAutoClearTimeOut: 180
Changed to 3 minutes. Thank you.

2021-06-01 02:04 UTC, vgupta-mickey approved these changes

2021-06-01 02:04 UTC, vgupta-mickey approved these changes
Looks good

2021-06-10 08:57 UTC, victor-polyansky approved these changes

2021-06-11 04:10 UTC, eddiepavkovic approved these changes
ok merge now but it'll have to change again when #813 merges.

2021-06-11 08:24 UTC, merged

2021-06-11 08:27 UTC, victor-polyansky commented
> ok merge now but it'll have to change again when #813 merges.

@eddiepavkovic we will update prefixes in #813 before it's merged