[OBSDEF-8124] Use the zk image that supports non-default ns by default
EMCECS/charts pull request #794
Opened 2021-05-24 10:25 UTC by CraneShiEMC

## Purpose
[OBSDEF-8124](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8124)
Use the zk image that supports non-default ns in OpenShift by default

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
The default zk image with the fix that supports non-default ns has been verified correct and workable

2021-05-24 13:10 UTC, realAaronWu approved these changes

2021-05-24 20:32 UTC, eddiepavkovic requested changes
Why are we updating this one when its going to be auto-update in build 74 when this is auto-set by release framework?

2021-05-24 20:34 UTC, eddiepavkovic commented on ecs-cluster/values.yaml
> +    tag: 0.2.10-176-09b4041 # rfw-update-this zookeeper-docker-image
we should be updating the latest/green component versions file zookeeper.
https://eos2git.cec.lab.emc.com/ECS/component-versions/tree/master/components/zookeeper

2021-05-25 01:52 UTC, realAaronWu commented on ecs-cluster/values.yaml
> +    tag: 0.2.10-176-09b4041 # rfw-update-this zookeeper-docker-image
Thanks, I think it is not necessary to do so here.

2021-05-25 14:10 UTC, closed without merging