[OBSDEF-3870] Make KAHM only set custom values
EMCECS/charts pull request #808
Opened 2021-06-02 22:50 UTC by tmarcu

Currently we build the chart values annotation by transforming the
*entire* .Values file into json, which outputs all settings including
ones that we do not pass in. This makes it impossible to pick out
specific settings and only propagate those during an upgrade.
The default values should be enough to bring up a component, and we only
need to keep track of a small subset that must be kept over an upgrade.
Doing the install this way lets us upgrade KAHM by only changing the
main chart-version annotation, and the rest of the subcharts and values
will be automatically updated from the new chart version.

Signed-off-by: Tudor Marcu <Tudor.Marcu@emc.com>

## Purpose
[OBSDEF-3870](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-3870)

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
Applying the yaml file brings up kahm, updating the chart version upgrades the component and brings in new sub-components automatically.

2021-06-02 23:00 UTC, Bjohnson131 approved these changes

2021-06-02 23:00 UTC, Bjohnson131 commented on kahm/templates/custom.yaml
> +    storageClass: {{ .Values.postgresqlHA.persistence.storageClass }}
Is there a reason to separate these two classes?

2021-06-02 23:02 UTC, tmarcu commented on Makefile
> +	cd kahm; \
it goes back to the previous dir after this make target automatically. Annoyingly it leaves right after the yq line too so that's why I added another cd line

2021-06-02 23:03 UTC, tmarcu commented on kahm/templates/custom.yaml
> +    storageClass: {{ .Values.postgresqlHA.persistence.storageClass }}
I'm not sure if we want postgresql to use the same global storageclass, @vgupta-mickey  what do you think?

2021-06-03 01:02 UTC, vgupta-mickey requested changes

2021-06-03 01:02 UTC, vgupta-mickey commented on Makefile
> +	--set postgresqlHA.persistence.storageClass=${STORAGECLASSNAME} \
it can't be postgresqlHA. It has to be postgresql-ha.

The storageclass  for the postgres has to be set in the postgres sub-charts only.

2021-06-03 01:02 UTC, vgupta-mickey commented on kahm/templates/custom.yaml
> +postgresqlHA:
postgresql-ha

2021-06-03 01:14 UTC, tmarcu commented on kahm/templates/custom.yaml
> +postgresqlHA:
this isn't possible, helm go templating does not allow hyphens `-` in templating params, so I literally cannot use that word for this.

2021-06-03 01:15 UTC, tmarcu commented on Makefile
> +	helm template --show-only templates/custom.yaml kahm ../kahm  -n ${NAMESPACE} \
It is not possible to do this with it in the top level, helm template will ignore anything not in the templates directory

2021-06-03 12:30 UTC, vgupta-mickey commented on Makefile
> +	helm template --show-only templates/custom.yaml kahm ../kahm  -n ${NAMESPACE} \
Correct. Maybe we need some discussion on this. 
we need to think from all the platforms. Vmware, Openshift, kind, minikube, and any other platform.
KAHM  charts will be available as open-source. So, it shouldn't have anything specific to vmware.

2021-06-03 12:31 UTC, vgupta-mickey commented on kahm/templates/custom.yaml
> +postgresqlHA:
need to talk. It will break the functionality.

2021-06-03 12:33 UTC, vgupta-mickey commented on kahm/templates/custom.yaml
> +    storageClass: {{ .Values.postgresqlHA.persistence.storageClass }}
postgres charts has different word for setting the storage class.

2021-06-03 12:34 UTC, vgupta-mickey commented on Makefile
> +	helm template --show-only templates/kahm-app.yaml kahm ../kahm  -n ${NAMESPACE} ${HELM_KAHM_ARGS} \
HELM_KAHM_ARGS should be when we generate customvalues.yaml

2021-06-03 16:58 UTC, tmarcu commented
@vgupta-mickey reverting back to postgresql-ha brings up the new postgres components successfully, and the helm template can accept `-` with the `index .Values <path> <to> <thing>` syntax

2021-06-03 22:32 UTC, eddiepavkovic commented on Makefile
> +	helm template --show-only templates/custom.yaml kahm ../kahm  -n ${NAMESPACE} ${HELM_KAHM_ARGS} \
i'd prefer we name the file `kahm-custom-values.yaml` to indicate we're using this as a way to customize values for kahm.

2021-06-03 22:32 UTC, eddiepavkovic commented on kahm/templates/custom.yaml
> +global:
run yamllint on new files.
add 
```
---
``` 
at the top of the file.

2021-06-03 22:32 UTC, eddiepavkovic commented on kahm/templates/custom.yaml
> +createkahmappResource: {{ .Values.createkahmappResource }}
newline?  or maybe its already there.

2021-06-03 22:32 UTC, eddiepavkovic commented on kahm/templates/kahm-app.yaml
> +    nautilus.dellemc.com/chart-values: {{ .Files.Get "customvalues.json" | toJson }}
does this work on a regular `make build CHARTS=kahm`  if the file is not there?

we still need to allow installs of kahm via `helm install`

2021-06-03 22:45 UTC, vgupta-mickey commented on kahm/templates/kahm-app.yaml
> +    nautilus.dellemc.com/chart-values: {{ .Files.Get "customvalues.json" | toJson }}
would new yaml file under template create problem when you install the charts using helm install?

Did you try the mutation using new kahm charts into the install-controller?

2021-06-03 22:52 UTC, tmarcu commented on kahm/templates/kahm-app.yaml
> +    nautilus.dellemc.com/chart-values: {{ .Files.Get "customvalues.json" | toJson }}
I fixed this, thanks for pointing it out it wasn't workign on regular helm.

2021-06-03 23:27 UTC, tmarcu commented on Makefile
> +	helm template --show-only templates/custom.yaml kahm ../kahm  -n ${NAMESPACE} ${HELM_KAHM_ARGS} \
fixed

2021-06-04 12:26 UTC, vgupta-mickey approved these changes

2021-06-04 12:26 UTC, vgupta-mickey commented on Makefile
> +	rm -rf kahm/customvalues.*
why are we removing this line?

2021-06-04 15:16 UTC, tmarcu commented on Makefile
> +	rm -rf kahm/customvalues.*
it's not useful it's just an intermediate file so I can use helm's templating engine to generate a second values.yaml type of file, and I need to do some back and forth conversions to make it possible. We only keep **kahm/kahm-custom-values.yaml** and generate our intermediate files from that, but it has to remain _out_ of templates or helm installs break.

2021-06-04 15:16 UTC, merged