Feature obsdef 8295 4083 8020 log forwarding from UI
EMCECS/charts pull request #812
Opened 2021-06-03 16:34 UTC by maheshkulkarni4

## Purpose
[OBSDEF-4083 ](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-4083 )
OBSDEF-4083 - vsphere plugin: add support for log forwarding

[OBSDEF-8295 ](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8295 )
OBSDEF-8295 - Update Replica counts for plugin UI and Graphql Deploument

[OBSDEF-8020 ](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8020 )
OBSDEF-8020 - Replication page should get enabled without enabling the flag.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-03 18:59 UTC, ben-schumacher commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +      {{- if not .Values.logReceiver.type }}
```suggestion
```

2021-06-04 11:39 UTC, maheshkulkarni4 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +      {{- if not .Values.logReceiver.type }}
Resolved.

2021-06-04 12:12 UTC, vgupta-mickey approved these changes

2021-06-04 12:13 UTC, eddiepavkovic requested changes
the changes don't look right. 

from @vazhem  we simply need to add 3 labels to the pod.

2021-06-04 12:15 UTC, maheshkulkarni4 commented on objectscale-portal/values.yaml
> +#
yeah.. without this 
{{- if not .Values.logReceiver.type }} 
fails.

2021-06-04 12:16 UTC, maheshkulkarni4 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +      {{- if not .Values.logReceiver.type }}
This is adding the rsyslog sidecar container... @victor-polyansky  mentioned it on the Ticket too and confirmed that this is needed 
https://jira.cec.lab.emc.com/browse/OBSDEF-4083

2021-06-04 13:00 UTC, eddiepavkovic requested changes

2021-06-04 13:01 UTC, victor-polyansky commented on objectscale-portal/values.yaml
> +#
I guess this `logReceiver` config is some old configuration for logging, it's not used in the objectscale logging now and can be removed. Checks for `{{- if not .Values.logReceiver.type }}` can be removed too.

2021-06-04 15:39 UTC, maheshkulkarni4 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +  replicas: 2
Yes

2021-06-04 18:37 UTC, vazhem approved these changes

2021-06-07 07:27 UTC, maheshkulkarni4 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +      {{- if not .Values.logReceiver.type }}
This is removed now as discussed.

2021-06-07 07:27 UTC, maheshkulkarni4 commented on objectscale-portal/values.yaml
> +#
This is removed as well.

2021-06-07 11:06 UTC, eddiepavkovic commented
Did the labels actually get added. Look at my pr #821    you may need a change to values.yaml

2021-06-07 17:01 UTC, eddiepavkovic approved these changes
ok.  after a bunch of merges and tests its working better now.
approving and merging.

2021-06-07 17:02 UTC, merged