[OBSDEF-4081] decks kahm logging fuel injection
EMCECS/charts pull request #821
Opened 2021-06-07 04:07 UTC by eddiepavkovic

## Purpose
[OBSDEF-4081](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-4081)
_List the changes for this PR_

## PR checklist
- [x] make test passed
- [x] make build passed
- [ ] helm install <chart> passed
- [x] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
### New labels in Pod for logging fuel injection:
```
Labels:       app.kubernetes.io/name=decks
              app.kubernetes.io/namespace=dellemc-eddie-4081-domain-c8
              name=decks
              objectscale.dellemc.com/logging-inject=true
              objectscale.dellemc.com/logging-inject-rsyslog=false
              objectscale.dellemc.com/logging-release-name=decks
              objectscale.dellemc.com/sp-integrated=true
              pod-template-hash=7bd5fc576c
              release=decks

Labels:       app.kubernetes.io/name=decks-support-store
              app.kubernetes.io/namespace=dellemc-eddie-4081-domain-c8
              io.kompose.service=decks-support-store
              objectscale.dellemc.com/logging-inject=true
              objectscale.dellemc.com/logging-inject-rsyslog=false
              objectscale.dellemc.com/logging-release-name=decks
              objectscale.dellemc.com/sp-integrated=true
              pod-template-hash=646b4bbdf7
              release=decks

Labels:       app=kahm
              app.kubernetes.io/namespace=dellemc-eddie-4081-domain-c8
              name=kahm
              objectscale.dellemc.com/logging-inject=true
              objectscale.dellemc.com/logging-inject-rsyslog=false
              objectscale.dellemc.com/logging-release-name=kahm
              objectscale.dellemc.com/sp-integrated=true
              pod-template-hash=7486f69ffd
              release=kahm
```

2021-06-07 13:20 UTC, vgupta-mickey approved these changes

2021-06-07 15:51 UTC, victor-polyansky requested changes

2021-06-07 15:51 UTC, victor-polyansky commented on decks/templates/decks.yaml
> +{{ include "common-monitoring-lib.logging-inject-labels" . | indent 8 }}
Adding labels with `common-monitoring-lib.logging-inject-labels` won't work with DECKS/KAHM as there is a special case because they are installed in the objectscale namespace, but separately from the objectscale manager.

The label 'objectscale.dellemc.com/logging-release-name' will be rendered as 
`objectscale.dellemc.com/logging-release-name=decks` but it should contain the release name of the objectscale-manager. The release name is `objectscale-manager` on vsphere and any on the Openshift.

Could you add the labels directly and pass release name of the objectscale-manager as helm value?
```
app.kubernetes.io/namespace={{ .Release.Namespace }}
objectscale.dellemc.com/logging-inject=true
objectscale.dellemc.com/logging-release-name={{ .Values.global.objectscale_release_name }}
```

We use `global.objectscale_release_name` to pass the value to [logging-injector](https://github.com/EMCECS/charts/blob/76f944df21d5adb40ddea1a8e41b68c876f05683/Makefile#L307).

2021-06-07 17:19 UTC, eddiepavkovic commented on decks/templates/decks.yaml
> +{{ include "common-monitoring-lib.logging-inject-labels" . | indent 8 }}
thanks for the review @victor-polyansky - but this makes it more complicated.  Can we make it so that there's a label or annotation that indicates the "release" where we can find the rsyslog pods then all other components can "auto" pick this up on their install.

2021-06-07 18:49 UTC, victor-polyansky commented on decks/templates/decks.yaml
> +{{ include "common-monitoring-lib.logging-inject-labels" . | indent 8 }}
we are going to get rid of this label in [MONITORING-1041](https://jira.cec.lab.emc.com/browse/MONITORING-1041), but currently we need it.

2021-07-06 17:13 UTC, victor-polyansky commented on decks/templates/decks.yaml
> +{{ include "common-monitoring-lib.logging-inject-labels" . | indent 8 }}
@eddiepavkovic MONITORING-1041 was done, now we don't need `objectscale.dellemc.com/logging-release-name` label.
Changes in this PR are valid.

2021-07-06 17:13 UTC, victor-polyansky approved these changes

2021-10-02 01:46 UTC, eddiepavkovic commented
alread fixed with PR: https://github.com/EMCECS/charts/pull/1055

2021-10-02 01:46 UTC, closed without merging

2021-10-02 01:47 UTC, eddiepavkovic commented
#1055