[OBSDEF-8704]
EMCECS/charts pull request #823
Opened 2021-06-07 16:03 UTC by vgupta-mickey

added platform, watch_ns, and schedule as container argument to telem…etry reports

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-07 16:55 UTC, eddiepavkovic requested changes
can we make it simpler:
if `--watch_ns` is set then watch a namespace only.  if not then watch all.

```
--watch_ns "dellemc-objectscale-domain-c10" 
```

2021-06-07 16:55 UTC, eddiepavkovic commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +{{- end }}
can we make this simpler.  if the argument is not there then watch all namespaces.
```suggestion
{{- if neq .Values.global.watchAllNamespaces true }}
            - -watch_ns
            - metadata.namespace
{{- end}}
```

2021-06-07 17:17 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +{{- end }}
just to keep this consistent with other watch namespace. We will provide the args with either empty string or it's own namespace.

2021-06-08 13:00 UTC, eddiepavkovic approved these changes
its fine.  it still looks odd to pass in an empty string to watch all namespaces.  hope it works ok in k8s.

2021-06-08 13:01 UTC, eddiepavkovic commented
Please fill in the testing section.  there's no problem with passing in an empty string to `--watch_ns ""` ?

2021-06-08 16:05 UTC, youminhan approved these changes

2021-06-08 16:09 UTC, merged