[OBSDEF-8958] revert dcm service type to loadBalancer
EMCECS/charts pull request #827
Opened 2021-06-07 21:31 UTC by sumithreddy

## Purpose
[OBSDEF-8958](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-8958)
Gateway service requires token authentication changes for dcm API's.
Reverting back dcm service type for 0.75

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-07 21:55 UTC, eddiepavkovic requested changes

2021-06-07 21:55 UTC, eddiepavkovic commented on objectscale-dcm/values.yaml
> +  type: LoadBalancer
can we eventually route this thru objectscale-gateway.

2021-06-07 21:56 UTC, eddiepavkovic commented
Please run the custom-ci job to ensure no regressions.

2021-06-07 22:01 UTC, sumithreddy commented on objectscale-dcm/values.yaml
> +  type: LoadBalancer
There is some issue with authenticating the headers we generally send for DCM API's ATM on gateway service.
It will be routed through gateway after those issues are handled. That's the end goal.

It should be addressed on 0.66

2021-06-07 22:02 UTC, hldnova approved these changes

2021-06-07 22:47 UTC, sumithreddy commented
> Please run the custom-ci job to ensure no regressions.

https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/173/

2021-06-08 01:12 UTC, eddiepavkovic approved these changes
ok, lgmt

2021-06-08 01:12 UTC, merged