[OBSDEF-8318] remove cached binaries from repo
EMCECS/charts pull request #842
Opened 2021-06-11 11:34 UTC by aoberezin

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-11 12:52 UTC, nikolay-t approved these changes

2021-06-11 12:52 UTC, nikolay-t commented on Makefile
> +	for CHART in ${ALL_CHARTS}; do \
Is it important to keep same processing order as in build (i.e. correspondingly to dependencies)?

2021-06-11 12:52 UTC, nikolay-t commented on .gitignore
> +**/charts/*.tgz
If we add this ignore, can we add ignore for docs as well?

2021-06-11 13:01 UTC, aoberezin commented on .gitignore
> +**/charts/*.tgz
Yes, if we are ready to drop docs from here.

2021-06-11 13:47 UTC, eddiepavkovic submitted a review, later dismissed
These aren't cached.  these are required and should be merged.

2021-06-11 13:52 UTC, eddiepavkovic commented
Whats the change here, there's no jira, nothing checked off on the checklist.  did we run the chart-custom-ci?

2021-06-11 15:06 UTC, aoberezin commented
> These aren't cached. these are required and should be merged.
Required for what? Final charts will contain it anyway.

> Whats the change here, there's no jira, nothing checked off on the checklist. did we run the chart-custom-ci?
Testing is in progress, the PR is a draft

2021-06-11 17:03 UTC, aoberezin commented on Makefile
> +	for CHART in ${ALL_CHARTS}; do \
Changed to Build Order

2021-06-11 19:10 UTC, nikolay-t commented
@eddiepavkovic goal of this PR is to remove binaries from EMCECS/charts repository. we will remove docs directory and we will remove all cached charts in */charts/*.
This means:
1. Users will run additional command `make build`, `make update-dependencies` to download/recreate needed charts or we can add it to `make package`
2. Release charts previously stored in docs will be accessible in separate repository https://github.com/EMCECS/charts-bin

2021-06-18 14:02 UTC, eddiepavkovic commented on .gitignore
> +**/charts/*.tgz
I'm concerned about this change.  if we're no longer including the dependent charts then when we want to run a quick development test say:
```
git checkout -b bugfix-OBSDEF-nnnn-fixing-xyz
<make code changes>
helm install objs-mgr ./objectscale-manger --set global.registry=asdrepo.isus.emc.com:8099
```
this will fail right?  because the dependent charts won't be there like it is now.

2021-06-30 10:03 UTC, antonbassin approved these changes

2021-06-30 13:39 UTC, eddiepavkovic requested changes
just to understand what happens when we build install-controller, where does it pick up the built charts from "docs" or charts-bin.

Does charts-bin have all the READMEs on how to download and install objectscale?

2021-06-30 13:39 UTC, eddiepavkovic commented on Makefile
> +update-dependencies:
change we change this to `chart-dep`

2021-06-30 15:01 UTC, aoberezin commented on Makefile
> +update-dependencies:
sure

2021-06-30 15:03 UTC, aoberezin commented
> just to understand what happens when we build install-controller, where does it pick up the built charts from "docs" or charts-bin.
> 
> Does charts-bin have all the READMEs on how to download and install objectscale?

1. It picks charts from DOCS, which is why make build will be required before install-controller build

2. Does charts-bin have all the READMEs on how to download and install objectscale?
Not yet.

2021-06-30 16:17 UTC, eddiepavkovic approved these changes
ok changes look fine after our zoom session.

thanks

2021-06-30 17:41 UTC, merged