[OBSDEF-9149] update atlas operator version
EMCECS/charts pull request #843
Opened 2021-06-11 17:33 UTC by sumithreddy

## Purpose
[OBSDEF-9149](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9149)
update atlas operator version

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-11 17:35 UTC, skripg approved these changes

2021-06-11 17:53 UTC, vdranov approved these changes

2021-06-14 17:57 UTC, merged

2021-06-14 18:21 UTC, eddiepavkovic requested changes

2021-06-15 01:15 UTC, sumithreddy commented on atlas-operator/values.yaml
> +  tag: 0.14.0 # rfw-update-this atlas-operator-docker-image
Noted. Will leave it to release jobs for updating versions

2021-06-15 01:15 UTC, sumithreddy commented on atlas-operator/values.yaml
> +  tag: 0.14.0 # rfw-update-this atlas-operator-docker-image
Noted. Will leave it to release jobs for tag updates