[OBSDEF-9175] dcm encryption key
EMCECS/charts pull request #846
Opened 2021-06-15 01:01 UTC by skripg

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-15 02:51 UTC, skripg commented on objectscale-dcm/templates/encryption-key.yaml
> +  enckey: {{ randAlphaNum 32 | lower | b64enc }}
@eddiepavkovic  This should work only during first install. It should not be regenerated after upgrade for example, right? I am asking because it is a sensitive field, if it is recreated then we will not be able to decrypt customer secrets.

2021-06-15 02:54 UTC, eddiepavkovic requested changes
1. please fill out the checklist
2. make sure you're running helm 3.5.4 or greater
3. Make sure you run the jenkins job from the checklist.
thanks

2021-06-15 02:54 UTC, eddiepavkovic commented on objectscale-dcm/templates/encryption-key.yaml
> +  enckey: {{ randAlphaNum 32 | lower | b64enc }}
yea you'll need to set the `helm-pre-install` hook so that the secret is only installed once.

2021-06-15 02:56 UTC, skripg commented on objectscale-dcm/templates/encryption-key.yaml
> +  enckey: {{ randAlphaNum 32 | lower | b64enc }}
I should add this to the annotations ?

2021-06-15 17:59 UTC, skripg commented
Thank you @eddiepavkovic ! Tests are passed with the updated helm.

2021-06-15 21:53 UTC, sumithreddy commented on objectscale-dcm/templates/encryption-key.yaml
> +  namespace: {{ .Release.Namespace}}
indentation for namespace? is it part of labels

2021-06-15 21:54 UTC, sumithreddy approved these changes
LGTM except the indentation for one of the label

2021-06-16 01:17 UTC, eddiepavkovic approved these changes
nice work.  thanks for making the updates.

2021-06-16 18:43 UTC, skripg commented on objectscale-dcm/templates/encryption-key.yaml
> +  namespace: {{ .Release.Namespace}}
no, it is in metadata as far as I know.

2021-06-16 18:44 UTC, merged