[OBSDEF-9084]  SNMP notifier
EMCECS/charts pull request #847
Opened 2021-06-15 12:32 UTC by vgupta-mickey

## Purpose
[OBSDEF-9084](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9084)
This is DellEMC SNMP Notifier chart which will configure the SNMP notifiers to send the SNMP traps to the configured SNMP manager.
It is a generic chart which is product independent. Each product can install it as a sub-chart to their product.
The notifier chart will need to configure the following 2 info as mandatory to run the basic v2c SNMP notifier ( default community string is "public").
1. product name
2. SNMP manager host name
helm install snmp-notifier ./snmp-notifier --set product=objectscale --set snmpServer.host=10.241.218.59

In order to install v3 SNMP notifier, a user needs to provide more information. Multiple authentication flavors are available:

1) Auth only v3
helm install snmp-notifier ./snmp-notifier --set product=objectscale --set snmpServer.host=10.241.218.59,snmpServer.version=v3,snmpServer.username=snmpv3_objectscale_md5_des,snmpServer.securityLevel=authi,snmpServer.authPass=admin1234,snmpServer.authProtocol=MD5

2)Auth + Priv v3
helm install snmp-notifier ./snmp-notifier --set product=objectscale --set snmpServer.host=10.241.218.59,snmpServer.version=v3,snmpServer.username=snmpv3_objectscale_md5_des,snmpServer.securityLevel=authpriv,snmpServer.authPass=admin1234,snmpServer.authProtocol=MD5,snmpServer.privPass=admin1234,snmpServer.privProtocol=DES

The chart is designed very  compact and using _helper.yaml heavily to keep the chart short and clean.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
```
vinod@ubuntu:~/go/src/dellcharts/charts$ k get service,pod,deployment,secret,notifiers,app,configmap -l release=snmp-notifier
NAME                                              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
service/snmp-notifier-objectscale-snmp-notifier   ClusterIP   10.96.167.79   <none>        50051/TCP   12h

NAME                                                           READY   STATUS    RESTARTS   AGE
pod/snmp-notifier-objectscale-snmp-notifier-65cbfc99c4-mcnlq   1/1     Running   0          11h

NAME                                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/snmp-notifier-objectscale-snmp-notifier   1/1     1            1           12h

NAME                                                                      READY
notifier.kahm.emcecs.github.com/snmp-notifier-objectscale-snmp-notifier   

NAME                                                             TYPE                        VERSION   OWNER   READY   AGE
application.app.k8s.io/snmp-notifier-objectscale-snmp-notifier   objectscale-snmp-notifier   2.76.0                    12h

NAME                                                           DATA   AGE
configmap/snmp-notifier-objectscale-snmp-notifier-app-config   3      12h
```

2021-06-15 12:41 UTC, d1rksm33ts approved these changes

2021-06-15 14:01 UTC, eddiepavkovic requested changes

2021-06-15 14:01 UTC, eddiepavkovic commented on snmp-notifier/templates/snmp-server-secret.yaml
> +  privPass: {{ .Values.snmpServer.privPass }}
is this cleartext.

2021-06-15 14:01 UTC, eddiepavkovic commented on snmp-notifier/values.yaml
> +  # tag: # rfw-update-this snmp-notifier-image
```suggestion
  tag: # rfw-update-this snmp-notifier-image
```
remove comment so that its auto-updated by release framework.

2021-06-15 16:08 UTC, vgupta-mickey commented on snmp-notifier/values.yaml
> +# productName: objectscale - required field to pass in using --set
supportAssist has productName but not under global.product. should we keep in the sameway or global.product is better option?

2021-06-15 16:10 UTC, vgupta-mickey commented on snmp-notifier/templates/snmp-server-secret.yaml
> +  privPass: {{ .Values.snmpServer.privPass }}
No.  secrets are base64 encoded

2021-06-17 18:23 UTC, eddiepavkovic reviewed
Please run the jenkins job and fill out the checklist.

Also put in a few lines of the testing you did.

2021-06-17 18:31 UTC, eddiepavkovic commented on snmp-notifier/README.md
> +5. Application Configmap to define rules to send TEST TRAPs
is this still accurate?

2021-06-17 18:31 UTC, eddiepavkovic commented on snmp-notifier/README.md
> + 2. privProtocol
does this mean we also need authPass and authProtocol?

2021-06-17 18:31 UTC, eddiepavkovic commented on snmp-notifier/README.md
> +In order to test SNMP TRAPs, a test-trap event need to generate in the same namepace where the snmp-notifier is configured. The following command need to execute in order to send SNMP TEST TRAP.
```suggestion
In order to test SNMP traps, use the following command to generate a test trap event for kahm: 
```

2021-06-17 18:31 UTC, eddiepavkovic commented on snmp-notifier/README.md
> +
```
kubectl get app | grep snmp
```
Then use the name above to insert it into the following command for the test trap event:

2021-06-17 18:31 UTC, eddiepavkovic commented on snmp-notifier/templates/app-configmap.yaml
> +            - Check if the community string is configured correct in case of v2c SNMP manager
```suggestion
        - symptomid: SNMPNOTI-1000
          description: Dell EMC SNMP Notifier is unable to send traps due to connection or authetication failure for the product {{.Values.product}}
          remedies:
            - Check if the SNMP user is configured with the correct authetication parameters
            - Check if the engineID is matching with the engineID configured for the user in SNMP manager
            - Check if the SNMP notifier is configured with the correct SNMP manager host/IP address and port
            - Check if the community string is configured correct in case of v2c SNMP manager
```

2021-06-17 22:19 UTC, vgupta-mickey commented on snmp-notifier/README.md
> +5. Application Configmap to define rules to send TEST TRAPs
yes

2021-06-17 22:23 UTC, vgupta-mickey commented on snmp-notifier/templates/app-configmap.yaml
> +            - Check if the community string is configured correct in case of v2c SNMP manager
why do you think SNMPNOTI-1000 is better than  SNMPNOT-1? This is just a free format string. correct? do we have any schema that we should start numbers with 1000? if yes, then we need to change. 
if I need to change, it needs to get change in code, charts and test-traps and do testing again. do you think we should do it?

2021-06-17 22:23 UTC, vgupta-mickey commented on snmp-notifier/README.md
> + 2. privProtocol
correct.

2021-06-17 23:26 UTC, eddiepavkovic commented on snmp-notifier/templates/app-configmap.yaml
> +            - Check if the community string is configured correct in case of v2c SNMP manager
Yes, it makes it easier to read so you're not confusing it with a lowercase `l` and it allows you to categorize it for future events.  `1000-1999` configuration `2000-2999` etc...

2021-06-17 23:30 UTC, eddiepavkovic commented on snmp-notifier/templates/app-configmap.yaml
> +            - Check if the community string is configured correct in case of v2c SNMP manager
is it server or Manager?  
```suggestion
            - Verify the SNMP credentials are configured with the correct authetication values
            - Verify thee engineID matches with the engineID configured for the product in the SNMP server
            - Verify the product SNMP notifier is configured with the correct host/IP address and port
            - Verify connectivity to the SNMP server, check firewalls, network routing etc...
            - Verify the SNMP v2c configuration has the correct community string
```

2021-06-17 23:34 UTC, eddiepavkovic commented on snmp-notifier/values.yaml
> +# productName: objectscale - required field to pass in using --set
that was because ESE uses `productName`

2021-06-18 18:09 UTC, tmarcu commented on snmp-notifier/README.md
> +If securityLevel is "authpriv", then the following parameters are mandatory in addtion to the above
```suggestion
If securityLevel is "authpriv", then the following parameters are mandatory in addition to the above
```

2021-06-18 18:09 UTC, tmarcu commented on snmp-notifier/README.md
> +If securityLevel is "auth", then the following parameters are mandatory in addtion to the above
```suggestion
If securityLevel is "auth", then the following parameters are mandatory in addition to the above
```

2021-06-18 18:09 UTC, tmarcu commented on snmp-notifier/templates/NOTES.txt
> +Use the helm install command below to deploy dell-ese
```
Use the helm install command below to deploy dell-ese
```
dell-ese or snmp?

2021-06-18 18:37 UTC, eddiepavkovic approved these changes
conditionally approved.
1. Please post the link of the custom-ci job if/when it works
2. Please fix the typos that tudor found especially the visible ones.

2021-06-18 18:37 UTC, eddiepavkovic commented on snmp-notifier/templates/NOTES.txt
> +Use the helm install command below to deploy dell-ese
fix typos when you get a chance.

2021-06-18 19:35 UTC, merged