[OBSDEF-8255] Add labels for Fedsvc and IAM Atlas pods
EMCECS/charts pull request #852
Opened 2021-06-16 21:57 UTC by voa808

## Purpose
[OBSDEF-8255] Add labels for Fedsvc and IAM Atlas pods

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-custom-ci/202/

_Paste the output of your helm install/vSphere7 deployment testing here_
https://jira.cec.lab.emc.com/browse/OBSDEF-8255?focusedCommentId=6144492&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6144492

2021-06-16 22:03 UTC, sumithreddy approved these changes
Labels LGTM. Please update the checklist

2021-06-16 22:04 UTC, sumithreddy commented
> Labels LGTM. Please update the checklist

I merged component lables on these atlas deployment files https://github.com/EMCECS/charts/pull/848

2021-06-16 22:22 UTC, voa808 commented
@sumithreddy ohk, in that case, we can reject this PR and close it.

2021-06-16 23:34 UTC, sumithreddy commented on federation/templates/atlas_v1beta1_fedcluster.yaml
> +{{ include "common-monitoring-lib.logging-inject-labels" . | indent 4 }}
common-monitoring-lib chart dependencies should be added.

2021-06-16 23:34 UTC, sumithreddy commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +{{ include "common-monitoring-lib.logging-inject-labels" . | indent 4 }}
common-monitoring-lib chart dependencies should be added.

2021-06-17 01:19 UTC, sumithreddy requested changes
add dependent monitoring charts

2021-06-17 18:38 UTC, voa808 commented on federation/templates/atlas_v1beta1_fedcluster.yaml
> +{{ include "common-monitoring-lib.logging-inject-labels" . | indent 4 }}
Done, thanks!

2021-06-17 20:20 UTC, sumithreddy approved these changes

2021-06-17 20:23 UTC, SeemaTahaliyani approved these changes

2021-06-17 20:30 UTC, merged