[OBSDEF-9326] allow KAHM to connect to remote postgres instance in case of the Atlantic platform
EMCECS/charts pull request #856
Opened 2021-06-17 16:44 UTC by vgupta-mickey

KAHM can disable the local postgres instance and can connect to the centralized postgres database with the following command. In order to connect to the remote instance, KAHM needs username, password, dbname, ip and port of the remote postgres db.
There was a bug where hostname want setting properly. 

## Purpose
[OBSDEF-9326](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9326)
_List the changes for this PR_

## PR checklist
- [ x] make test passed
- [ x] make build passed
- [x ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-17 16:57 UTC, eddiepavkovic requested changes
please fill out the testing section and run this job:
 https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

2021-06-17 16:57 UTC, eddiepavkovic commented on kahm/templates/postgress-secrets.yaml
> +  dbname: {{ required "database must be specified" .Values.db.postgres.database }}
if this is required does it mess up vsphere  & openshift installs?  do we need to update any docs for this?

2021-06-17 17:02 UTC, vgupta-mickey commented on kahm/templates/postgress-secrets.yaml
> +  dbname: {{ required "database must be specified" .Values.db.postgres.database }}
by default we have username, password, dbname so the openshift and the vSpehere deployment won't have any impact with this.

2021-06-18 18:04 UTC, tmarcu approved these changes

2021-06-18 18:43 UTC, eddiepavkovic approved these changes
ok cool.

2021-06-18 19:34 UTC, merged