[OBSDEF-9089] Added events and issue rules to report SNMP traps
EMCECS/charts pull request #857
Opened 2021-06-17 18:04 UTC by vgupta-mickey

## Purpose
[OBSDEF-9089](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9089)
Added a new SNMP notifier as  a part of issue and event rules to report TRAPs to the SNMP server.
- All issue rules will add SNMP notifier to report traps on creating/updating/clearing any issue for all applications
- All Critical, Warning, Error events will be reported to SNMP server for ObjectStore and Objectscale-operator

## PR checklist
- [ x] make test passed
- [ x] make build passed
- [x ] helm install <chart> passed
- [x ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-17 19:13 UTC, vazhem commented on ecs-cluster/alerts/issues/1006_BUCKET_HARD_QUOTA_EXCEEDED_issue.yaml
> +  notifiers:
Ideally I would prefer to not specify every possible notifier for every issue rule.
Issue should have an attribute like channel: ESE / Customer / All.
This way when you would add other notifiers like smtp, syslog, there will be no need to specify all possible supported notifiers in every issue definition...

2021-06-17 20:22 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/1006_BUCKET_HARD_QUOTA_EXCEEDED_issue.yaml
> +  notifiers:
I think we can discuss on this but not on this PR. It needs KAHM infrastructure code change and I don’t think that we have time to change that now.

2021-06-17 22:29 UTC, eddiepavkovic requested changes
Please run custom-charts ci jenkins job.

2021-06-17 22:35 UTC, eddiepavkovic requested changes
typo on notifier.

Also please indicate what testing was done... if possible show objecstore, license or objectscale-manager snmp traps being received.

2021-06-17 22:35 UTC, eddiepavkovic commented on supportassist/templates/supportassist-app-configmap.yaml
> +          - {{.Values.product}}-snmp-notifiers
typo
```suggestion
          - {{.Values.product}}-snmp-notifier
```

2021-06-18 18:46 UTC, eddiepavkovic approved these changes
nice.  lgmt

2021-06-21 21:38 UTC, ben-schumacher approved these changes

2021-06-21 22:20 UTC, merged