Changes to create servicelogin shared secret and mount it in IAM and DCM
EMCECS/charts pull request #862
Opened 2021-06-18 21:39 UTC by SeemaTahaliyani

…DCM.

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-18 22:08 UTC, lipak2345 commented on ecs-cluster/templates/shared_secret.yaml
> +  name: {{ .Release.Name }}-mgmt-serviclogin-shared-secret
nitpick: There is a typo in **service** (missing e)

2021-06-18 23:02 UTC, eddiepavkovic requested changes

2021-06-18 23:02 UTC, eddiepavkovic commented on ecs-cluster/templates/shared_secret.yaml
> +stringData:
Is  this a secret that shouldn't change on upgrade?   Is so we need to add
Annotations that'll prevent it from changing

2021-06-19 23:34 UTC, SeemaTahaliyani commented on ecs-cluster/templates/shared_secret.yaml
> +stringData:
I think we will make it not change on upgrade. I need to add below annotations correct?
```
"helm.sh/hook": "pre-install"
"helm.sh/hook-delete-policy": "before-hook-creation"
```

2021-06-21 16:07 UTC, SeemaTahaliyani commented on ecs-cluster/templates/shared_secret.yaml
> +stringData:
@eddiepavkovic added annotations. Please  check. Thanks

2021-06-21 16:25 UTC, SeemaTahaliyani commented on ecs-cluster/templates/shared_secret.yaml
> +  name: {{ .Release.Name }}-mgmt-serviclogin-shared-secret
Thanks :) fixed it.

2021-06-21 18:20 UTC, SeemaTahaliyani commented
Made sure secret is created and mounted as needed by the federation svc service login

```
10:~/EMCECS # k get secret | grep shared
ecs-cluster-mgmt-servicelogin-shared-secret                       Opaque                                1      10s
mgmt-servicelogin-shared-secret                                   Opaque                                1      40m


10:~/EMCECS/charts # k exec -it objectscale-iam-c85cbfc4d-j2kcn bash
bash-4.4# cd /etc/mgmt/sharedsecret/
bash-4.4# cat key 
Bq0Qy9giIopNApzNaQvxzVIhW4Nh0rdI5PvkZksXzMJZnXknk18VAvB28u1QVEAHNJrervGKqY6Fq5OJMXF88VOT0YgPhgWL18EHzaEMy9mIwPRVatxzfHouSBYHFZ5xbash-4.4# ^C
bash-4.4# exit
exit
command terminated with exit code 130
10:~/EMCECS/charts # k exec -it objectscale-dcm-64d8f4499d-67gfb bash
bash-4.4# cat /etc/mgmt/sharedsecret/key 
Bq0Qy9giIopNApzNaQvxzVIhW4Nh0rdI5PvkZksXzMJZnXknk18VAvB28u1QVEAHNJrervGKqY6Fq5OJMXF88VOT0YgPhgWL18EHzaEMy9mIwPRVatxzfHouSBYHFZ5xbash-4.4# 

10:~/EMCECS # k exec -it ecs-cluster-s3-7f4bc67458-tdmlv bash
Defaulting container name to s3.
Use 'kubectl describe pod/ecs-cluster-s3-7f4bc67458-tdmlv -n default' to see all of the containers in this pod.
bash-4.4# cd /etc/m
magic       mgmt/       modprobe.d/ motd        mtab        
bash-4.4# cd /etc/mgmt/sharedsecret/
bash-4.4# cat key 
Sg11zHt7ya1pGJ7ueYXp2Vru2YObRBQ4Uo8ouueBIfXIjAclVau6aYiATYF7nalgmvhvo1W8eGgGEytS4FQhfheNV0YtL7Eb9kvJUdCL7vYtR1tlWEgtjWnxETuLYwZybash-4.4# exit
exit
10:~/EMCECS # k exec -it ecs-cluster-geo-6bcf596465-wsmlv bash
Defaulting container name to geo.
Use 'kubectl describe pod/ecs-cluster-geo-6bcf596465-wsmlv -n default' to see all of the containers in this pod.
bash-4.4# cat /etc/mgmt/sharedsecret/key 
Sg11zHt7ya1pGJ7ueYXp2Vru2YObRBQ4Uo8ouueBIfXIjAclVau6aYiATYF7nalgmvhvo1W8eGgGEytS4FQhfheNV0YtL7Eb9kvJUdCL7vYtR1tlWEgtjWnxETuLYwZybash-4.4# 
bash-4.4# exit
exit
10:~/EMCECS # k exec -it ecs-cluster-geoservice-57ff9f846f-jhktg bash
Defaulting container name to geoservice.
Use 'kubectl describe pod/ecs-cluster-geoservice-57ff9f846f-jhktg -n default' to see all of the containers in this pod.
bash-4.4# cat /etc/mgmt/sharedsecret/key
Sg11zHt7ya1pGJ7ueYXp2Vru2YObRBQ4Uo8ouueBIfXIjAclVau6aYiATYF7nalgmvhvo1W8eGgGEytS4FQhfheNV0YtL7Eb9kvJUdCL7vYtR1tlWEgtjWnxETuLYwZybash-4.4# 
bash-4.4# exit
exit
10:~/EMCECS # k exec -it ecs-cluster-control-757ffbfd55-z5jsd bash
Defaulting container name to control.
Use 'kubectl describe pod/ecs-cluster-control-757ffbfd55-z5jsd -n default' to see all of the containers in this pod.
bash-4.4# cat /etc/mgmt/sharedsecret/key
Sg11zHt7ya1pGJ7ueYXp2Vru2YObRBQ4Uo8ouueBIfXIjAclVau6aYiATYF7nalgmvhvo1W8eGgGEytS4FQhfheNV0YtL7Eb9kvJUdCL7vYtR1tlWEgtjWnxETuLYwZybash-4.4#
```

2021-06-21 18:35 UTC, eddiepavkovic commented on ecs-cluster/templates/shared_secret.yaml
> +stringData:
ok looks good.

2021-06-21 18:35 UTC, eddiepavkovic approved these changes
ok

2021-06-21 18:47 UTC, lipak2345 approved these changes

2021-06-21 20:29 UTC, merged