add watch_ns for license-usage
EMCECS/charts pull request #869
Opened 2021-06-23 22:09 UTC by SarahAFochs

## Purpose
[OBSDEF-9047](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9047)
Add watch_ns arg for license-usage

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing

2021-06-30 21:52 UTC, vgupta-mickey requested changes

2021-06-30 21:52 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +           - metadata.namespace
change it {{ .Release.Namespace }}

2021-07-06 17:55 UTC, vgupta-mickey approved these changes

2021-07-07 01:26 UTC, youminhan approved these changes

2021-07-07 03:48 UTC, eddiepavkovic approved these changes
ok

2021-07-07 04:07 UTC, merged