[OBSDEF-7152] Add symptomID and remedy for preupdate checks
EMCECS/charts pull request #874
Opened 2021-06-24 23:47 UTC by tmarcu

Signed-off-by: Tudor Marcu <Tudor.Marcu@emc.com>

## Purpose
[OBSDEF-7152](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7152)

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-06-30 22:28 UTC, vgupta-mickey requested changes

2021-06-30 22:28 UTC, vgupta-mickey commented on decks/alerts/issues/OBJSC-HC-1000_PRE_UPDATE_issue.yaml
> +        - label: SymptomID
Each application should have unique SymptomID

2021-06-30 22:28 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/OBJSC-HC-1000_PRE_UPDATE_issue.yaml
> +          value: OBJSC-HC-1000
should be different

2021-06-30 22:28 UTC, vgupta-mickey commented on kahm/alerts/issues/OBJSC-HC-1000_PRE_UPDATE_issue.yaml
> +          value: OBJSC-HC-1000
need unique symptomID

2021-06-30 22:28 UTC, vgupta-mickey commented on objectscale-manager/alerts/issues/OBJSC-HC-1000_PRE_UPDATE_issue.yaml
> +          value: OBJSC-HC-1000
unique SymptomID

2021-07-01 00:57 UTC, tmarcu commented on decks/alerts/issues/OBJSC-HC-1000_PRE_UPDATE_issue.yaml
> +        - label: SymptomID
ah I misunderstood. So maybe there should be some app identifier or should I only increment the number for other apps?

2021-07-01 17:58 UTC, vgupta-mickey commented on decks/alerts/issues/OBJSC-HC-1000_PRE_UPDATE_issue.yaml
> +        - label: SymptomID
App identifier

2021-07-06 20:11 UTC, vgupta-mickey requested changes

2021-07-06 20:11 UTC, vgupta-mickey commented on decks/templates/decks-app-configmap.yaml
> +          symptomID: "OBJSC-HC-1000"
DECKS-HC-1000

2021-07-06 20:11 UTC, vgupta-mickey commented on kahm/templates/kahm-app-configmap.yaml
> +        symptomID: "OBJSC-HC-1000"
KAHM-HC-1000

2021-07-06 20:11 UTC, vgupta-mickey commented on kahm/templates/kahm-app-configmap.yaml
> +        symptomID: "OBJSC-HC-1000"
under eventRules?
https://github.com/EMCECS/charts/blob/72934ed38a5ab3331458eb5f8fbf9a348c977aca/objectscale-manager/templates/objectscale-manager-app-configmap.yaml#L19-L24

2021-07-06 20:11 UTC, vgupta-mickey commented on decks/templates/decks-app-configmap.yaml
> +          symptomID: "OBJSC-HC-1000"
https://github.com/EMCECS/charts/blob/72934ed38a5ab3331458eb5f8fbf9a348c977aca/objectscale-manager/templates/objectscale-manager-app-configmap.yaml#L19-L24

2021-07-06 20:11 UTC, vgupta-mickey commented on objectscale-manager/templates/objectscale-manager-app-configmap.yaml
> +          symptomID: "OBJSC-HC-1000"
OBJSC-MGR-HC-1000

2021-07-06 22:18 UTC, vgupta-mickey approved these changes
Looks good but please test before the merge

2021-07-07 14:55 UTC, eddiepavkovic approved these changes
ok

2021-07-08 19:24 UTC, merged