[OBSDEF-9719][OBSDEF-10301] - Change charts+graphql to launch mgr, decks, kahm, logging-injector for vSphere and OpenShift
EMCECS/charts pull request #916
Opened 2021-07-20 22:23 UTC by eddiepavkovic

## Purpose
- Update charts to remove app yamls from vSphere plugins and app  resources
- In association there's a graphql change that'll launch objectscale apps: objectscale-manager, logging-injector, kahm, decks by creating apps and letting install-controller do the install.
- 
[OBSDEF-9719](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9719)
[OBSDEF-10301](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-10301)

- These chart changes basically widdle down the vsphere plugin to just the core,  objectscale-portal, graphql & install-controller.
- Same launching will happen for all platforms
- Eventually retiring the "objectscale-install.sh" script

## PR checklist
- [x] make test passed
- [x] make build passed
- [x] helm install <chart> passed
- [x] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

### OpenShift install:
```
helm install objs ./objectscale-portal --set global.registry=asdrepo.isus.emc.com:8099 --set global.storageClassName=csi-baremetal-sc-hddlvg  --set global.platform=OpenShift --set global.watchAllNamespaces=false 

graphql logs:
2021-07-20T21:33:45Z	INFO	server/main.go:125	GraphQL server version: 0.77.0-668.776689bc listening on port 8080
2021-07-20T21:33:45Z	INFO	mutations/objectscale_apps.go:238	Creating application: objectscale-manager version: 0.77.0
2021-07-20T21:33:45Z	INFO	server/startapps.go:97	ObjectScale application objectscale-manager installed
2021-07-20T21:33:45Z	INFO	mutations/objectscale_apps.go:238	Creating application: logging-injector version: 0.77.0
2021-07-20T21:33:45Z	INFO	server/startapps.go:97	ObjectScale application logging-injector installed
2021-07-20T21:33:46Z	INFO	mutations/objectscale_apps.go:238	Creating application: kahm version: 2.77.0
2021-07-20T21:33:46Z	INFO	server/startapps.go:97	ObjectScale application kahm installed
2021-07-20T21:33:46Z	INFO	mutations/objectscale_apps.go:238	Creating application: decks version: 2.77.0
2021-07-20T21:33:46Z	INFO	server/startapps.go:97	ObjectScale application decks installed

└─ $ ▶  kubectl get app
NAME                     TYPE                  VERSION   OWNER   READY   AGE
csi-baremetal            csi-baremetal                                   22h
decks                    decks                 2.77.0                    47m
kahm                     kahm                  2.77.0                    47m
logging-injector         logging-injector      0.77.0                    47m
objectscale-manager      objectscale-manager   0.77.0                    47m
objectscale-monitoring                                                   46m

─ $ ▶  helm list
NAME                  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                                    	APP VERSION
csi-baremetal         	default  	1       	2021-07-15 08:35:21.983522128 -0400 EDT	deployed	csi-baremetal-deployment-0.2.2-39.5850f57	0.2.2      
csi-baremetal-operator	default  	1       	2021-07-15 08:34:59.239660892 -0400 EDT	deployed	csi-baremetal-operator-0.2.2-39.5850f57  	0.2.2      
decks                 	default  	1       	2021-07-20 21:37:37.311940794 +0000 UTC	deployed	decks-2.77.0                             	2.77.0     
kahm                  	default  	1       	2021-07-20 21:37:04.455085703 +0000 UTC	deployed	kahm-2.77.0                              	2.77.0     
logging-injector      	default  	2       	2021-07-20 21:33:46.181267765 +0000 UTC	deployed	logging-injector-0.77.0                  	0.77.0     
objectscale-manager   	default  	1       	2021-07-20 21:33:46.549900802 +0000 UTC	deployed	objectscale-manager-0.77.0               	0.77.0     
objs                  	default  	1       	2021-07-20 17:33:39.017197978 -0400 EDT	deployed	objectscale-portal-0.77.0                	0.77.0     

```

### vSphere 7 U2 on andre:

### vSphere 7 U3

2021-07-20 23:12 UTC, Bjohnson131 approved these changes
The make comment is take or leave. 
I'm concerned about the change to the GraphQL chart.

2021-07-20 23:12 UTC, Bjohnson131 commented on Makefile
> +	# rm -rf ${TEMP_PACKAGE}/crds
instead of commenting these out, it may be worth putting them into their own make job, which can still be used from master, but isn't part of the buildpath. saves some headache in case these are used later.

2021-07-20 23:12 UTC, Bjohnson131 commented on objectscale-graphql/templates/graphql-deployment.yaml
> +        - -startapps
I'm pretty sure the '- --' artifact is only used for debugging....

2021-07-22 15:25 UTC, SarahAFochs approved these changes

2021-07-22 15:25 UTC, SarahAFochs commented on Makefile
> +    --set graphql.enabled=true \
```suggestion
	--set graphql.enabled=true \
```

2021-07-22 18:39 UTC, tmarcu approved these changes
I did not test this myself, but looks ok

2021-07-23 10:26 UTC, vgupta-mickey requested changes

2021-07-23 10:26 UTC, vgupta-mickey commented on Makefile
> +	sed ${SED_INPLACE} 's/app.kubernetes.io\/managed-by: Helm/app.kubernetes.io\/managed-by: nautilus/g' ${TEMP_PACKAGE}/yaml/apps/objectscale-manager-app.yaml
I am not sure If I understand the change completely.

We decided that we will make things simple after your changes. That being said,  we will not have any custom file generation in charts.
Also, we will not generate any application resources when we create the plugin - either vSphere or OpenShift.

1. The Makefile should generate all the yaml files for the  plugin only that being said, it should run helm template on objectscale-vsphere only.
2. No helm template  on apps
3. All custom value files should be removed from the charts template directory 
4.  A custom-value.yaml for each chart should exist at the same location  where the values.yaml file is. This custom-value.yaml file is a sample file for customers/users to use it for their installation.
5.  All the vSphere related custom changes must go under vSphere directory if we need to pass custom values for the application in the graphql.
6. All the openshift related changes will go under openshift directory

2021-07-23 10:26 UTC, vgupta-mickey commented on Makefile
> +	-f values.yaml -f customvalues.yaml > ../${TEMP_PACKAGE}/yaml/apps/objectscale-manager-app.yaml
we don't need any more - helm template --show-only templates/objectscale-manager

2021-07-23 10:26 UTC, vgupta-mickey commented on Makefile
>  create-decks-app: create-temp-package
we don't need

2021-07-23 10:26 UTC, vgupta-mickey commented on Makefile
>  create-kahm-app: create-temp-package
we don't need

2021-07-23 10:26 UTC, vgupta-mickey commented on helm-controller/templates/deployment.yaml
> +            - name: POD_NAMESPACE
why GLOBAL registry goes to install-controller directly. GRAPHL passes that info to the install-controller.

2021-07-23 10:26 UTC, vgupta-mickey commented on objectscale-graphql/templates/graphql-deployment.yaml
> +          value: {{ .Values.global | toJson | quote }}
I thought we don't want to pass GLOBAL_VALUES as one blob.

2021-07-23 10:26 UTC, vgupta-mickey commented on objectscale-graphql/templates/graphql-deployment.yaml
> +        {{- if .Values.kahmCustomValues }}
I thought that these custom values will be maintained in custom-values.yaml file and we will read the file from there for each application.

2021-07-23 10:26 UTC, vgupta-mickey commented on objectscale-graphql/values.yaml
> +### kept for reference
this whole block should have been in a file to keep grapql values.yaml file clean.

2021-07-30 02:06 UTC, vgupta-mickey approved these changes

2021-07-30 02:07 UTC, vgupta-mickey reviewed
Please make sure that we cleanup the custom template files from the charts

2021-08-02 03:24 UTC, eddiepavkovic commented on objectscale-graphql/templates/graphql-deployment.yaml
> +          value: {{ .Values.global | toJson | quote }}
keeping it for debugging and how its deployed.  its helped a lot with deployments.

2021-08-02 23:37 UTC, merged