Bugfix obsdef 6074
EMCECS/charts pull request #933
Opened 2021-08-09 12:30 UTC by maheshkulkarni4

## Purpose
[OBSDEF-6074](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6074)
Added Pod Anttiaffinity rules for ObjectScale Portal, so that two pods of objectscale-portal wont deploy on same node. 

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-08-11 15:05 UTC, Bjohnson131 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +            - dellemc-uiprim78-domain-c44
? pretty sure this isn't right..

2021-08-11 15:08 UTC, eddiepavkovic requested changes
remove hard coded namespaces.

2021-08-11 15:08 UTC, eddiepavkovic commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +            - dellemc-uiprim78-domain-c44
remove hardcoded namespaces.

2021-08-11 15:25 UTC, SarahAFochs commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +            - dellemc-uiprim78-domain-c44
```suggestion
            - {{ .Release.Namespace }}
```

2021-08-11 20:32 UTC, vgupta-mickey commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> -    spec:
moved spec at wrong place. Need to fix it. I am going to fix it for you and push the changes.

2021-08-11 20:48 UTC, vgupta-mickey approved these changes

2021-08-11 20:49 UTC, vgupta-mickey approved these changes
I fixed your spec. Please test now.

2021-08-12 16:19 UTC, maheshkulkarni4 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +            - dellemc-uiprim78-domain-c44
Done. Please review.

2021-08-12 16:19 UTC, maheshkulkarni4 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +            - dellemc-uiprim78-domain-c44
Done

2021-08-12 16:19 UTC, maheshkulkarni4 commented on objectscale-portal/templates/objectscale-portal-deployment.yaml
> +            - dellemc-uiprim78-domain-c44
Done

2021-08-12 17:21 UTC, merged