[OBSDEF-7255] ability to pass storageclass for atlas
EMCECS/charts pull request #935
Opened 2021-08-10 19:44 UTC by sumithreddy

## Purpose
[OBSDEF-7255](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7255)
configurable storageclass for atlas deployments

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-08-10 20:46 UTC, skripg approved these changes

2021-08-10 20:56 UTC, eddiepavkovic requested changes
please run custom-ci job and post the result before merging.

2021-08-10 20:56 UTC, eddiepavkovic commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +      storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}
so if neither one is set this is blank and i think it picks up the default storage class or fails.   did we test this?

2021-08-10 21:07 UTC, sumithreddy commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +      storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}
I am running deployments now for various scenarios.

https://github.com/EMCECS/charts/blob/4c7f0a0878a2179aa5c1c0ea0cd34399eb52c804/ecs-cluster/templates/ecs-cluster.yaml#L79 -> worked fine with no issues till now. Need to check if omitEmpty set somewhere

2021-08-10 21:30 UTC, sumithreddy commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +      storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}
storageClass and registry are always passed during deployment but will add a safety check anyway
Thanks!

2021-08-10 21:37 UTC, sumithreddy commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +      storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}
done

2021-08-11 00:40 UTC, SeemaTahaliyani commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +      storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}
can you explain this a bit please, is it possible for both of below to be true
.Values.global.storageClassName  .Values.atlas.persistence.storageClassName, how is storageClass set then?
`storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}`

2021-08-11 08:27 UTC, sumithreddy commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +      storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}
default <default val> <override val>

2021-08-11 15:44 UTC, SeemaTahaliyani approved these changes

2021-08-11 19:58 UTC, sumithreddy commented
> please run custom-ci job and post the result before merging.

done and listed

2021-08-11 19:59 UTC, sumithreddy commented on objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
> +      storageClassName: {{ default .Values.global.storageClassName .Values.atlas.persistence.storageClassName }}
@eddiepavkovic made necessary changes. can you approve the PR?

2021-08-13 21:17 UTC, eddiepavkovic approved these changes
lgmt

2021-08-13 21:33 UTC, merged