[OBSDEF-10894] add Alert for CRR bug detect
EMCECS/charts pull request #938
Opened 2021-08-12 10:49 UTC by chengmx1025

## Purpose
[OBSDEF-10894](https://jira.cec.lab.emc.com/browse/OBSDEF-10894)
_List the changes for this PR_
  add new AlertType REPLICATION_BUG_DETECTED

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-08-12 12:40 UTC, eddiepavkovic requested changes
The name has to change this is shown to customers.  We can't have the world bug

2021-08-12 14:06 UTC, vgupta-mickey requested changes

2021-08-12 14:06 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/12007_REPLICATION_BUG_DETECTED.yaml
> +  name: "REPLICATION_BUG_DETECTED"
It should be problem specific

2021-08-13 04:12 UTC, chengmx1025 commented on ecs-cluster/alerts/issues/12007_REPLICATION_BUG_DETECTED.yaml
> +  name: "REPLICATION_BUG_DETECTED"
could I change the error code name to "UNKNOWN_REPLICATION_ERROR_DETECTED" ?

2021-08-13 06:38 UTC, eddiepavkovic requested changes

2021-08-13 06:38 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/12007_UNKNOWN_REPLICATION_ERROR_DETECTED.yaml
> +  name: "UNKNOWN_REPLICATION_ERROR_DETECTED"
What does this mean?   How will customers know what remedies 
To perform if they hit this problem.  

We shouldn't be vague like this.  It's just going to have customers 
Frustrated and call dell.

2021-08-13 09:21 UTC, dingr5 commented on ecs-cluster/alerts/issues/12007_UNKNOWN_REPLICATION_ERROR_DETECTED.yaml
> +  name: "UNKNOWN_REPLICATION_ERROR_DETECTED"
I suppose we could modify the name but I think this Alert is send to Dell only channel.

2021-08-24 07:47 UTC, dingr5 approved these changes

2021-08-24 07:54 UTC, chengmx1025 commented
Hi @eddiepavkovic @vgupta-mickey,
I've renamed the Alert code to REPLICATION_EVENT_RETRY_LIMIT_EXCEEDED.
And also, this alert will be only visible to EMC OE team.

2021-08-30 03:49 UTC, merged

2021-08-30 03:55 UTC, eddiepavkovic commented
Why was my review request removed.

2021-09-01 03:15 UTC, dingr5 commented
> Why was my review request removed.

Hi @eddiepavkovic , sorry for the delayed reply. We have already reply addressed the changed based on the comment and re-request for 6 days. So we thought there should be no more comments and we should be able to continue. Will double check with you next time.