[OBSDEF-10328] Install controller network policy
EMCECS/charts pull request #942
Opened 2021-08-13 21:39 UTC by SarahAFochs

## Purpose
[OBSDEF-10328](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-10328)
Grant install-controller networkpolicy access.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
error
```
2021-08-13T19:33:26.505Z	ERROR	installer.helm-reconciler	unable to install releaseArgs	{"name": "test2", "namespace": "end-user-test", "chartVersion": "0.79.0", "error": "template: ecs-cluster/templates/networkpolicy.yaml:2:23: executing \"ecs-cluster/templates/networkpolicy.yaml\" at <lookup \"networking.k8s.io/v1\" \"NetworkPolicy\" .Release.Namespace \"objectscale-allow-all\">: error calling lookup: networkpolicies.networking.k8s.io \"objectscale-allow-all\" is forbidden: User \"system:serviceaccount:svc-objectscale-domain-c10:install-controller\" cannot get resource \"networkpolicies\" in API group \"networking.k8s.io\" in the namespace \"end-user-test\""}
```
resolve
```
 Name:         objectscale-allow-all                                                                                                                                                                                                                                  
 Namespace:    end-user-test                                                                                                                                                                                                                                          
 Created on:   2021-08-13 13:28:50 -0700 PDT                                                                                                                                                                                                                          
 Labels:       app.kubernetes.io/managed-by=Helm                                                                                                                                                                                                                      
 Annotations:  meta.helm.sh/release-name: test5                                                                                                                                                                                                                       
               meta.helm.sh/release-namespace: end-user-test                                                                                                                                                                                                          
 Spec:                                                                                                                                                                                                                                                                
   PodSelector:     <none> (Allowing the specific traffic to all pods in this namespace)                                                                                                                                                                              
   Allowing ingress traffic:                                                                                                                                                                                                                                          
     To Port: <any> (traffic allowed to all ports)                                                                                                                                                                                                                    
     From: <any> (traffic not restricted by source)                                                                                                                                                                                                                   
   Not affecting egress traffic                                                                                                                                                                                                                                       
   Policy Types: Ingress                                                                                                                                                                                                                                                           
```

2021-08-17 18:40 UTC, eddiepavkovic requested changes

2021-08-17 18:40 UTC, eddiepavkovic commented on helm-controller/templates/controller-rbac.yaml
> +      - '*'
do we need "mod" privs.  can we just get away with
```
- get 
- list 
```

2021-08-18 01:09 UTC, eddiepavkovic approved these changes
ok, lgmt

2021-08-18 02:15 UTC, youminhan approved these changes
👍

2021-08-18 02:20 UTC, merged