[OBSDEF-10964] added csi rbacs
EMCECS/charts pull request #943
Opened 2021-08-16 22:56 UTC by vgupta-mickey

## Purpose
[OBSDEF-10964](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-10964)
Add CSI rbacs to retrieve CSI-related resources in the service pod.

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-08-16 23:06 UTC, eddiepavkovic requested changes

2021-08-16 23:06 UTC, eddiepavkovic commented on service-pod/templates/rbac.yaml
> +{{- if eq .Values.global.platform "OpenShift" }}
Let's do ne VMware so that we pick up Atlantic and other platforms

2021-08-16 23:06 UTC, eddiepavkovic commented on service-pod/templates/rbac.yaml
> +  - list
@mishoyama  do we need to allow edits to o csu resources?

2021-08-17 06:52 UTC, mishoyama commented on service-pod/templates/rbac.yaml
> +  - list
Yes. modification might be needed.

2021-08-17 16:52 UTC, vgupta-mickey commented on service-pod/templates/rbac.yaml
> +  - list
Done

2021-08-17 20:39 UTC, eddiepavkovic reviewed
ok we should at least support Atlantic since it also uses CSI.

2021-08-17 20:40 UTC, eddiepavkovic commented
vinod fix the helm lint errors.  global.platform is not always passed in.

2021-08-18 15:13 UTC, eddiepavkovic approved these changes
please add atlantic when you get a chance.

2021-08-18 15:49 UTC, youminhan approved these changes

2021-08-18 15:49 UTC, merged