[OBSDEF-11053] add alert id for object store capacity usage exceed thre…
EMCECS/charts pull request #956
Opened 2021-08-23 06:44 UTC by lisaheyingying

…shold

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-11053)
_List the changes for this PR_
Add alert id for CAPACITY_USAGE_FOR_OBJECT_STORE_ERROR

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-08-23 08:36 UTC, vazhem commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_ERROR_issue.yaml
> +- description: "Capacity Usage for object store error"
please add remedie as well for this alert

2021-08-23 08:48 UTC, lisaheyingying commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_ERROR_issue.yaml
> +- description: "Capacity Usage for object store error"
sure

2021-08-23 09:13 UTC, vazhem commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_ERROR_issue.yaml
> +  defaultAutoClearTimeOut: 900
@victor-polyansky do we need auto-clear for sensor alerts?

2021-08-24 08:00 UTC, lisaheyingying commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_ERROR_issue.yaml
> +  defaultAutoClearTimeOut: 900
as discussed in slack, this is not needed

2021-08-24 08:25 UTC, vazhem commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-snmp-notifier
Is this only for user defined capacity alert?
What about SRS notification for built-in system capacity alert?

2021-08-24 10:27 UTC, lisaheyingying commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-snmp-notifier
1, SRS notification means what kind of notifiers? objectscale-supportassist-ese?
2.Warning and critical alert are use defined, so i think objectscale-snmp-notifier is enough
3.Error alert is system buit-in, what else notifier should i add?

2021-08-24 10:41 UTC, vazhem commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-snmp-notifier
right, ese notifier is for callhome.

having a single list here with two notifiers will make user-defined warning and critical also go to SRS which is not something we want

2021-08-24 13:09 UTC, victor-polyansky commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - matchon:
Please add match on Info SymptomID to support clearance.

2021-08-24 13:28 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - matchon:
Generally, I avoid having multiple SymptomIDs for a specific issue. However, in this case, Victor is right, you need to add SymptomID for creaing the issue.
Also remove the symptomIDs which you don't want to send to ESE in the list.
All the critical/warning/error events are sent to SNMP by default.

2021-08-25 08:40 UTC, hel11 commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - matchon:
ok. changed as your commnets

2021-08-25 11:34 UTC, victor-polyansky requested changes

2021-08-25 11:34 UTC, victor-polyansky commented on ecs-cluster/alerts/issues/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +  name: "CAPACITY_USAGE_FOR_OBJECT_STORE"
Let's use different names for "user" and "system" issue

2021-08-25 11:34 UTC, victor-polyansky commented on ecs-cluster/alerts/remedies/13003_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +- description: "Capacity Usage for object store"
Remedies should follow the format
```
- symptomid: <SYMPTOM_1>
  description: <DESCRIPTION>
  remedies:
    - <resolution action or link to KB>
- symptomid: <SYMPTOM_2>
  description: <DESCRIPTION>
  remedies:
    - <resolution action or link to KB>
```

Please refer to example:
https://github.com/EMCECS/charts/blob/master/ecs-cluster/alerts/remedies/1365_1366_LISTING_CONVERSION_THRESHOLD_EXCEEDED_remedies.yaml

2021-08-30 17:36 UTC, eddiepavkovic requested changes
sorry but this change doesn't make sense.  

we only need one issue & remedy file for these.

The ISSUE itself will indicate whether its a warning or error.  we don't need another ISSUE stating its an error

2021-08-30 17:40 UTC, eddiepavkovic requested changes
sorry but this change doesn't make sense.  

we only need one issue & remedy file for these.

The ISSUE itself will indicate whether its a warning or error.  we don't need another ISSUE stating its an error

2021-08-30 17:40 UTC, eddiepavkovic commented on ecs-cluster/alerts/issues/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-supportassist-ese
We don't need this file.  Why are we sending the ERROR to ESE for customer services?  When do we get the error?  when we cannot get the usage or something else.

2021-08-30 17:40 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13003_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore
We only need a single file for remedies.  its all the same message which should be fixed up.  we need to tell users other options and how to check.

2021-08-30 17:40 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13003_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +  description: Capacity usage for objectStore exceed warning threshold
```suggestion
  description: Capacity usage for the object store exceeded the warning threshold

```

2021-08-30 17:40 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13003_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +  description: Capacity usage for objectStore exceed critical threshold
```suggestion
  description: Capacity usage for the object store exceed the critical threshold

```

2021-08-30 17:40 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore， capacity usage has exceed 90%
This is an "Error" how can it be hardcoded to 90%... these are user defined right?

2021-08-31 01:53 UTC, lisaheyingying commented on ecs-cluster/alerts/remedies/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore， capacity usage has exceed 90%
waring &critical are user defined, error is system alert when capacity usage exceed 90%

2021-08-31 02:00 UTC, lisaheyingying commented on ecs-cluster/alerts/issues/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-supportassist-ese
1. ERROR means capacity usage exceeds 90% which means user data can not be written, so ESE is needed.
2. When capacity usgae exceed 90%, sensor framework will raise this error alert
3. @vazhem @vgupta-mickey  help double check my understanding, thanks very much

2021-08-31 02:46 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore， capacity usage has exceed 90%
but the order is:

1. Critical -  this shows as red in the GUI and they have to address it and most likely send to ESE
2. Error -  its an error
3. Warning
4. Normal

2021-08-31 07:23 UTC, victor-polyansky commented on ecs-cluster/alerts/remedies/13003_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore
@eddiepavkovic @lisaheyingying There's no strict requirement to match remedies and issue files.
All remedy files are rendered in configmap as is
https://github.com/EMCECS/charts/blob/master/ecs-cluster/templates/objectstore-app-configmap.yaml#L48
so we can put all symptoms into one file.

2021-08-31 07:23 UTC, victor-polyansky commented on ecs-cluster/alerts/issues/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-supportassist-ese
@lisaheyingying that's correct.

2021-08-31 07:27 UTC, lisaheyingying commented on ecs-cluster/alerts/remedies/13003_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore
ok, if you think put warning&critical&error remedies together will be better, i will merge the two remedies

2021-08-31 13:24 UTC, vgupta-mickey approved these changes
Looks good

2021-08-31 13:24 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13003_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +        # INFO
there is no INFO - it should be either Normal/Error/Critical/Warning

2021-08-31 13:24 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +        # INFO
Normal

2021-08-31 13:24 UTC, vgupta-mickey commented on ecs-cluster/alerts/issues/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-supportassist-ese
You could have one file for Issue and alerts and one file for remedies.

2021-09-01 01:02 UTC, lisaheyingying commented on ecs-cluster/alerts/issues/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - objectscale-supportassist-ese
the reason why i made two issue files is because that error vs warning&critical has different notification channel

2021-09-01 01:03 UTC, lisaheyingying commented on ecs-cluster/alerts/issues/13003_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +        # INFO
ok, will change INFO to NORMAL

2021-09-01 01:03 UTC, lisaheyingying commented on ecs-cluster/alerts/issues/13004_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +        # INFO
ok, will change INFO to NORMAL

2021-09-01 01:58 UTC, eddiepavkovic requested changes
Sorry lisa,  we're getting to the end of the release.  we need to make changes.
1. missing OBSDEF number in the PR
2. missing checklist 
3. filename is incorrect for remedies.

2021-09-01 02:21 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13003_13004_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +- symptomid: OBJST-13003
filename has to be renamed to 

```
13003_13004_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_remedies.yaml
```

2021-09-01 02:21 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13003_13004_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore
```suggestion
    - Check capacity usage for object store
    - Free up capacity on the object store
    - Expand the object store or adjust the thresholds 
```

2021-09-01 02:21 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13003_13004_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +    - Check capacity usage for objectStore， capacity usage has exceed 90%
```suggestion
    - The object store has exceeded 90% capacity
    - Free up capacity on the object store
    - Expand the object store if storage is available
```

2021-09-01 02:28 UTC, lisaheyingying commented on ecs-cluster/alerts/remedies/13003_13004_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_issue.yaml
> +- symptomid: OBJST-13003
done

2021-09-01 03:11 UTC, eddiepavkovic requested changes

2021-09-01 03:11 UTC, eddiepavkovic commented on ecs-cluster/alerts/remedies/13003_13004_13005_CAPACITY_USAGE_FOR_OBJECT_STORE_remedies.yaml
> +    - Check capacity usage for objectStore.
```suggestion
    - Check capacity usage for the object store
    - Free up capacity on the object store
    - Expand the object store or adjust the thresholds 
```

2021-09-01 03:15 UTC, eddiepavkovic approved these changes
ok g2g

2021-09-01 03:55 UTC, merged