[OBSDEF-10711] statefuldaemonset-operator: add new roles
EMCECS/charts pull request #971
Opened 2021-08-30 15:30 UTC by gusakk

Same as https://github.com/EMCECS/charts/pull/966 but to `release-objectscale-1.0-beta3`.

2021-08-30 15:38 UTC, victor-polyansky approved these changes

2021-08-30 17:34 UTC, Loki087 approved these changes

2021-08-30 17:45 UTC, eddiepavkovic requested changes
nothing in the testing output. 

did we test on OpenShift where i think we needed the `/finalizers` setting.

2021-08-30 21:01 UTC, gusakk commented
> nothing in the testing output.
> 
> did we test on OpenShift where i think we needed the `/finalizers` setting.

tested on vsphere only, you are right about finalizers on OpenShift, added these changes accordingly to this description:
https://jira.cec.lab.emc.com/browse/MONITORING-1064

2021-08-31 02:43 UTC, eddiepavkovic commented
Where is the checklist, the chart-custom-ci URL,  and did we test these changes on OpenShift?

2021-08-31 05:58 UTC, gusakk commented
> Where is the checklist, the chart-custom-ci URL, and did we test these changes on OpenShift?

https://asd-ecs-jenkins.isus.emc.com/job/monitoring-libs/job/objectscale-charts/job/feature-OBSDEF-10711-statefuldaemonset-operator-beta3/2/

tested on openshift manually

2021-08-31 13:09 UTC, eddiepavkovic approved these changes
g2g

2021-08-31 13:10 UTC, merged