[OBSDEF-10736] Update pravega crd to the latest version
EMCECS/charts pull request #982
Opened 2021-09-03 05:18 UTC by CraneShiEMC

## Purpose
[OBSDEF-10736](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-10736)
To comply with the latest pravega operator 0.5.5-254-92d86d32 to fix apk-tools security issue CVE-2021-30139, we need to also update pravega crd to the latest version

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

2021-09-03 05:37 UTC, eddiepavkovic requested changes
You need to run charts-custom-ci job.

2021-09-03 07:28 UTC, CraneShiEMC commented
> You need to run charts-custom-ci job.
Hi Eddie, the charts-custom-ci job for this PR https://asd-ecs-jenkins.isus.emc.com/view/ECS-Flex/job/charts-custom-ci/328/ is successful.

2021-09-03 07:29 UTC, CraneShiEMC commented
> You need to run charts-custom-ci job.

Hi Eddie, the charts-custom-ci job for this PR https://asd-ecs-jenkins.isus.emc.com/view/ECS-Flex/job/charts-custom-ci/328/ is successful.

2021-09-03 11:52 UTC, nikolay-t commented
@eddiepavkovic Please note that this PR results in increase of yaml file > 500KB, and vsphere processing script decides to gzip contents. Do we know if this is fine for possible use cases?

```
[INFO] Generating service definition for: id=objectscale, version=0.82.0-1286
[INFO] gzipping the YAML as size (549 KB) >= 500 KB
```

One side issue is that PR validation for this PR fails due to older python in infra devkit, which can't gzip yaml content. I created https://jira.cec.lab.emc.com/browse/OBSDEF-11474 to use different devkit with python 3.

2021-09-05 14:40 UTC, CraneShiEMC commented
> > You need to run charts-custom-ci job.
> 
> @eddiepavkovic I've finished running the charts-custom-ci job for this PR, https://asd-ecs-jenkins.isus.emc.com/view/ECS-Flex/job/charts-custom-ci/328/ , which was successful.

The charts-custom-ci job on the latest commit, https://asd-ecs-jenkins.isus.emc.com/view/ECS-Flex/job/charts-custom-ci/332/ , was also successful.

2021-09-05 16:32 UTC, eddiepavkovic commented
Does this still generate a yaml file or is the yaml file now gzipped?  can we reduce the size of the new pravega crd...

2021-09-06 03:02 UTC, CraneShiEMC commented
> Does this still generate a yaml file or is the yaml file now gzipped? can we reduce the size of the new pravega crd...

It seems that, with the updated python 3 lib on the devkit, the make package script can run without error to gzip the YAML larger than 500KB.

2021-09-06 04:32 UTC, eddiepavkovic approved these changes
ok i approve.

Please post to #ecs-flex that users will need to run the latest latest devkit or run the following on their build systems:

```
sudo apt install python-is-python3
```

```

2021-09-06 04:37 UTC, CraneShiEMC commented
> ok i approve.
> 
> Please post to #ecs-flex that users will need to run the latest latest devkit or run the following on their build systems:
> 
> ```
> sudo apt install python-is-python3
> ```

OK. Thank you very much, @eddiepavkovic !

2021-09-06 06:48 UTC, realAaronWu approved these changes

2021-09-06 06:48 UTC, merged